import type { SignalMapTimelineEvent } from "./types";
import { ISRAEL_IRAN_US_TIMELINE_DOT } from "../signalmap-israel-iran-us-conflict";
import { ARAB_SPRING_TIMELINE_DOT } from "../signalmap-arab-spring";
import { SIGNALMAP_BALKAN_AND_WAR_RANGES } from "../signalmap-war-canonical";
import { SIGNALMAP_OIL_TIMELINE } from "../signalmap-oil-canonical";

/** ~50 global + ~20 Iran anchor events for the interactive timeline MVP. */
export const SIGNALMAP_TIMELINE_SEED: SignalMapTimelineEvent[] = [
  // —— Global & war (20th c.) ——
  {
    id: "g-ww1-start",
    date_start: "1914-07-28",
    title_en: "World War I begins",
    title_fa: "آغاز جنگ جهانی اول",
    description_en: "Austro-Hungary declares war on Serbia; European alliances widen into global conflict.",
    description_fa: "امپراتوری اتریش-مجارستان به صربستان اعلام جنگ می‌کند و اتحادها به درگیری گسترده تبدیل می‌شود.",
    category: "war",
    tags: ["ww1", "europe"],
    importance: 3,
  },
  {
    id: "g-1929-crash",
    date_start: "1929-10-24",
    title_en: "Wall Street crash of 1929",
    title_fa: "سقوط بورس وال‌استریت ۱۹۲۹",
    description_en: "U.S. equity crash; beginning of the Great Depression worldwide.",
    description_fa: "سقوط بازار سهام آمریکا و آغاز رکود بزرگ در سطح جهان.",
    category: "global",
    tags: ["depression", "us"],
    importance: 3,
  },
  {
    id: "g-ww2-eu",
    date_start: "1939-09-01",
    title_en: "World War II: Germany invades Poland",
    title_fa: "جنگ جهانی دوم: حمله آلمان به لهستان",
    description_en: "Nazi Germany’s invasion of Poland; European war phase accelerates.",
    description_fa: "حمله نازی‌ها به لهستان و گسترش سریع جنگ در اروپا.",
    category: "war",
    tags: ["ww2", "europe"],
    importance: 3,
  },
  {
    id: "g-bretton-woods",
    date_start: "1944-07-01",
    date_end: "1944-07-22",
    title_en: "Bretton Woods Conference",
    title_fa: "کنفرانس برتون‌وودز",
    description_en: "Allied planning for post-war monetary order; dollar–gold parities and IMF/World Bank.",
    description_fa: "برنامه‌ریزی متفقین برای نظام پولی پساجنگ؛ دلار ـ طلا و بانک جهانی/صندوق.",
    category: "fx",
    tags: ["imf", "usd", "gold"],
    importance: 3,
  },
  {
    id: "g-ww2-end",
    date_start: "1945-05-08",
    title_en: "VE Day / war ends in Europe",
    title_fa: "پایان جنگ در اروپا",
    description_en: "Unconditional German surrender; end of hostilities in Europe (VE Day, 8 May 1945).",
    description_fa: "تسلیم بی‌قیدوششر آلمان؛ پایان نبرد در اروپا.",
    category: "war",
    tags: ["ww2", "europe"],
    importance: 3,
  },
  {
    id: "g-cold-start",
    date_start: "1947-03-12",
    title_en: "Truman Doctrine (Cold War frame)",
    title_fa: "دکترین ترومن (چارچوب جنگ سرد)",
    description_en: "U.S. pledge to support free peoples against subversion; often marked as Cold War framing.",
    description_fa: "تعهد آمریکا به حمایت «مردم آزاد» در برابر فشار؛ نقطه آغاز فریم جنگ سرد.",
    category: "global",
    tags: ["cold-war", "us"],
    importance: 2,
  },
  {
    id: "g-korea",
    date_start: "1950-06-25",
    title_en: "Korean War begins",
    title_fa: "آغاز جنگ کره",
    description_en: "North Korean forces cross the 38th parallel; UN forces intervene under U.S. leadership.",
    description_fa: "نیروهای کره‌شمالی از خط ۳۸ عبور می‌کنند و مداخله سازمان ملل آغاز می‌شود.",
    category: "war",
    tags: ["korea", "un"],
    importance: 2,
  },
  {
    id: "g-cuban",
    date_start: "1962-10-16",
    date_end: "1962-10-28",
    title_en: "Cuban Missile Crisis",
    title_fa: "بحران موشکی کوبا",
    description_en: "U.S.–Soviet confrontation over nuclear missiles in Cuba; closest Cold War near-miss to escalation.",
    description_fa: "برخورد ابرقدرت‌ها بر سر موشک هسته‌ای در کوبا؛ بحران اوج جنگ سرد.",
    category: "war",
    tags: ["cuba", "cold-war", "nuclear"],
    importance: 3,
  },
  {
    id: "g-nixon-gold",
    date_start: "1971-08-15",
    title_en: "Nixon shock (closing gold window)",
    title_fa: "شوک نیکسون (تعطیلی پنجره طلا)",
    description_en: "U.S. ends dollar convertibility to gold; move toward modern fiat and floating FX era.",
    description_fa: "پایان تبدیل‌پذیری دلار به طلا و گذار به نرخ شناور نسبی و نظام اهرمی.",
    category: "fx",
    tags: ["bretton-woods", "gold", "usd"],
    importance: 3,
  },
  {
    id: "g-volcker",
    date_start: "1979-10-06",
    title_en: "Volcker shock (Fed tightening)",
    title_fa: "شوک ولکر (تنگ‌ترشدن بانک مرکزی آمریکا)",
    description_en: "Federal Reserve under Volcker tightens to fight inflation; high global interest-rate spillovers.",
    description_fa: "تنگی شدید سیاست پولی آمریکا برای مقابله با تورم؛ اثر تطبیقی جهانی نرخ‌ها.",
    category: "fx",
    tags: ["fed", "inflation", "us"],
    importance: 2,
  },
  {
    id: "g-soviet-end",
    date_start: "1991-12-26",
    title_en: "Soviet Union dissolves",
    title_fa: "فروپاشی اتحاد شوروی",
    description_en: "USSR ceases to exist; fifteen republics and one dominant Russia successor state system.",
    description_fa: "اتحاد شوروی پایان می‌یابد و نظام میدان قدرت جهانی دگرگون می‌شود.",
    category: "global",
    tags: ["ussr", "europe", "russia"],
    importance: 3,
  },
  {
    id: "g-1997-asia",
    date_start: "1997-07-02",
    title_en: "Asian financial crisis (float break)",
    title_fa: "بحران مالی آسیا ۱۹۹۷",
    description_en: "Thailand abandons fixed baht; contagion to Indonesia, South Korea, and world credit channels.",
    description_fa: "رهاکردن بات و سرایت به اندونزی و کره جنوبی و کانال‌های اعتباری.",
    category: "fx",
    tags: ["asia", "imf", "contagion"],
    importance: 2,
  },
  {
    id: "g-9-11",
    date_start: "2001-09-11",
    title_en: "September 11 attacks (U.S.)",
    title_fa: "حملات ۱۱ سپتامبر (آمریکا)",
    description_en: "Coordinated attacks; major shift in U.S. security, Middle East, and global markets.",
    description_fa: "همدستی حملات و تحول امنیتی/ژئوپلیتیک و اثر بر بازارهای جهانی.",
    category: "global",
    tags: ["us", "security", "mideast"],
    importance: 3,
  },
  {
    id: "g-2008-lehman",
    date_start: "2008-09-15",
    title_en: "Lehman Brothers bankruptcy",
    title_fa: "ورشکستگی لِهمن برادرز",
    description_en: "G-SIB bank failure; acute phase of global financial crisis, severe USD funding stress.",
    description_fa: "سقوط بانک بزرگ سرمایه و فاز حاد بحران مالی جهانی و تنگی دلاری.",
    category: "fx",
    tags: ["gfc", "us", "banking"],
    importance: 3,
  },
  {
    id: "g-arab-spring",
    date_start: "2010-12-17",
    title_en: "Arab Spring begins (Tunisia)",
    title_fa: "شروع بیداری اسلامی (تونس)",
    description_en: "Self-immolation in Sidi Bouzid sparks regional protest wave and regime change in several states.",
    description_fa: "موج اعتراضات منطقه‌ای و تغییر حکومت در چند کشور پس از حادثه تونس.",
    category: "global",
    tags: ["mideast", "tunisia"],
    importance: 3,
  },
  {
    id: "g-covid-pheic",
    date_start: "2020-01-30",
    title_en: "WHO: COVID-19 Public Health Emergency",
    title_fa: "WHO: اضطرار بهداشتی کووید-۱۹",
    description_en: "WHO declares PHEIC; pandemic drives lockdowns, energy demand shock, and large fiscal/FX effects.",
    description_fa: "اعلام اضطرار جهانی؛ تعطیلی‌ها و شوک تقاضای انرژی و اثر مالی-ارزی بزرگ.",
    category: "global",
    tags: ["pandemic", "who", "lockdowns"],
    importance: 3,
  },
  {
    id: "g-ukraine-22",
    date_start: "2022-02-24",
    title_en: "Russia’s full-scale invasion of Ukraine",
    title_fa: "حمله گسترده روسیه به اوکراین",
    description_en: "Major land war in Europe; sanctions, energy/commodity dislocations, and refugee flow.",
    description_fa: "جنگ بزرگ در اروپا؛ تحریم و جابجایی انرژی/کالا و موج پناهجویی.",
    category: "war",
    tags: ["russia", "europe", "commodities"],
    importance: 3,
  },
  ...ISRAEL_IRAN_US_TIMELINE_DOT,
  // —— Iran-specific (domestic + foreign policy) ——
  {
    id: "ir-1953",
    date_start: "1953-08-19",
    title_en: "1953 Iranian coup d’état (context)",
    title_fa: "کودتای ۲۸ مرداد ۱۳۳۲ (زمینه)",
    description_en: "Overthrow of PM Mosaddegh; often cited in narratives of resource nationalism and U.S.–U.K. roles.",
    description_fa: "سقوط دولت مصدق و بازتعریف نفت و روابط واشنگتن/لندن (روایت‌های ملی‌گرایانه).",
    category: "iran",
    tags: ["coup", "mossadegh", "history"],
    importance: 2,
  },
  {
    id: "ir-rev-79",
    date_start: "1979-02-11",
    title_en: "1979 revolution (monarchy ends)",
    title_fa: "انقلاب ۵۷ (پایان سلسله پهلوی)",
    description_en: "Pahlavi monarchy replaced by Islamic Republic; reorientation of state, law, and foreign relations.",
    description_fa: "جایگزینی نظام سلطنت با جمهوری اسلامی و دگرگونی قانون/خارجی.",
    category: "iran",
    tags: ["1979", "pahlavi", "state"],
    importance: 3,
  },
  {
    id: "ir-hostage",
    date_start: "1979-11-04",
    date_end: "1981-01-20",
    title_en: "U.S. Embassy hostage crisis",
    title_fa: "بحران تسخیر سفارت آمریکا",
    description_en: "Diplomatic standoff, sanctions, and protracted U.S.–Iran rupture; oil markets in broader shock era.",
    description_fa: "توقف سیاسی-دیپلماتیک، تحریم‌ها و شکاف ماندگار واشنگتن-تهران (در ادوار نفتی/شوی).",
    category: "iran",
    tags: ["us", "diplomacy", "crisis"],
    importance: 3,
  },
  {
    id: "ir-iq-war-start",
    date_start: "1980-09-22",
    title_en: "Iran–Iraq war begins",
    title_fa: "آغاز جنگ ایران و عراق",
    description_en: "Full-scale border war; tanker war later; long macro and oil-market shadow over the region.",
    description_fa: "جنگ فرسایشی و بعداً جنگ تانکرها و سایه بلند اقتصادی-نفتی.",
    category: "war",
    tags: ["tanker-war", "gulf", "saddam"],
    importance: 3,
  },
  {
    id: "ir-iq-war-end",
    date_start: "1988-08-20",
    title_en: "UN ceasefire in Iran–Iraq war",
    title_fa: "آتش‌بس سازمان ملل (پایان جنگ)",
    description_en: "UNSCR 598 ceasefire after eight years; heavy human and physical capital cost on both states.",
    description_fa: "توقف تیرپساز هشت‌ساله و هزینه انسانی-سرمایه‌ای سنگین.",
    category: "war",
    tags: ["un", "ceasefire"],
    importance: 3,
  },
  {
    id: "ir-green",
    date_start: "2009-06-13",
    title_en: "2009 post-election protests (Green Movement)",
    title_fa: "اعتراضات ۱۳۸۸ (جنبش سبز)",
    description_en: "Widespread contestation after controversial election; domestic and diaspora media focal point.",
    description_fa: "تظاهرات وسیع پس از انتخابات؛ اثر در رسانه و جامعه مدنی.",
    category: "iran",
    tags: ["2009", "protests", "politics"],
    importance: 2,
  },
  {
    id: "ir-jcpoa",
    date_start: "2015-07-14",
    title_en: "Joint Comprehensive Plan of Action (JCPOA)",
    title_fa: "برنامه جامع اقدام مشترک (برجام)",
    description_en: "Iran nuclear deal; sanctions architecture altered; later U.S. withdrawal in 2018 (separate event).",
    description_fa: "توافق هسته‌ای و تغییر معماری تحریم (خروج آمریکا در ۹۷، رویداد جدا).",
    category: "global",
    tags: ["jcpoa", "sanctions", "nuclear"],
    importance: 3,
  },
  {
    id: "ir-jcpoa-exit",
    date_start: "2018-05-08",
    title_en: "U.S. withdrawal from JCPOA",
    title_fa: "خروج آمریکا از برجام",
    description_en: "U.S. reimposes unilateral maximum-pressure sanctions; FX and oil-export channels restructured.",
    description_fa: "بازتشدید فشار حداکثری و بازچینش کانال نفت-ارز.",
    category: "fx",
    tags: ["jcpoa", "sanctions", "trump"],
    importance: 3,
  },
  {
    id: "ir-soleimani",
    date_start: "2020-01-03",
    title_en: "Killing of Qasem Soleimani (U.S. strike)",
    title_fa: "کشته‌شدن قاسم سلیمانی (حمله آمریکا)",
    description_en: "Dramatic U.S.–Iran escalation; regional security, oil risk premium, and retaliatory dynamics.",
    description_fa: "تصعید شدید امنیتی-منطقه‌ای و اثر پریمیوم نفت و اقدام-واکنش.",
    category: "global",
    tags: ["mideast", "security", "qods"],
    importance: 3,
  },
  {
    id: "ir-wlf",
    date_start: "2022-09-16",
    title_en: "Mahsa Amini protests and Woman, Life, Freedom",
    title_fa: "اعترضات مرگ مهسا امینی «زن، زندگی، آزادی»",
    description_en: "Sustained nationwide protest wave after Jina (Mahsa) Amini’s death; wide international attention.",
    description_fa: "بازه اعترضات ملی-فراملی پس از فوت جینا (مهسا) امینی و توجه گسترده.",
    category: "iran",
    tags: ["2022", "wlf", "protests"],
    importance: 3,
  },
  {
    id: "ir-rial-stress-18",
    date_start: "2018-04-10",
    title_en: "Iran: sharp FX and parallel-market stress (illustrative anchor)",
    title_fa: "تنش شدید ارز و نرخ موازی (نقاط شاخص ۹۷-۹۸)",
    description_en: "Anchor for post-sanction shock period in rial/USD; exact dates of peaks vary (market microstructure).",
    description_fa: "لنگر دوره تنگی/شوک نرخ پس از فشار ۹۸؛ بیشینه دقیق روزانه ممکن است اختلاف داشته باشد.",
    category: "fx",
    tags: ["rial", "sanctions", "ir"],
    importance: 1,
  },
  {
    id: "oil-shale-rev",
    date_start: "2014-10-15",
    title_en: "U.S. shale: breakeven/oversupply phase (Brent context)",
    title_fa: "نفت شیل آمریکا: فاز عرضه مازاد (زمینه نفت‌برنت)",
    description_en: "Illustrative anchor for 2014–2016 price collapse driven partly by OPEC+shale; use as macro lens.",
    description_fa: "لنگر سال‌های سقوط قیمت ۲۰۱۴-۲۰۱۶ (اوپک+نفت تنگ‌شکن).",
    category: "oil",
    tags: ["brent", "shale", "oversupply"],
    importance: 2,
  },
  {
    id: "g-opec-plus-2016",
    date_start: "2016-11-30",
    title_en: "OPEC+ coordinated output framework (Vienna cycle)",
    title_fa: "نخستین توافق اصلی اوپک+ (چرخه مذاکرات ۲۰۱۶ وین)",
    description_en: "OPEC and non-OPEC (notably Russia) move toward explicit output management after 2014–2016 low prices; durable shift in oil market governance and spare-capacity logic.",
    description_fa: "روند هم‌مدیریتی تولید توسط اوپک و تولیدکنندگان غیر اوپک پس از فاز قیمت پایین؛ تغییر ماندگار در منطق مدیریت و ظرفیت مازاد نفت.",
    category: "oil",
    tags: ["opec-plus", "russia", "output-cuts"],
    importance: 2,
  },
  {
    id: "g-brexit-ref",
    date_start: "2016-06-23",
    title_en: "UK EU membership referendum (Brexit)",
    title_fa: "همه‌پرسی خروج بریتانیا از اتحادیه اروپا",
    description_en: "Vote to leave; multi-year policy and trade uncertainty, GBP volatility, institutional spillovers.",
    description_fa: "رأی خروج؛ سردرگمی چندساله تجارت-ارز/پاند.",
    category: "global",
    tags: ["europe", "gbp", "trade"],
    importance: 2,
  },
  {
    id: "g-isf-gulf-91",
    date_start: "1990-08-02",
    title_en: "Iraq invades Kuwait (Gulf War I)",
    title_fa: "حمله عراق به کویت (جنگ خلیج اول)",
    description_en: "Occupation; coalition response; very large, short oil-supply risk episode.",
    description_fa: "اشغال و پاسخ ائتلاف؛ ریسک عرضه نفتی بسیار بزرگ-کوتاه‌مدت.",
    category: "war",
    tags: ["gulf", "iraq", "kuwait", "oil"],
    importance: 1,
  },
  {
    id: "g-china-wto",
    date_start: "2001-12-11",
    title_en: "China joins WTO",
    title_fa: "ورود چین به سازمان تجارت جهانی",
    description_en: "Deeper global manufacturing integration; long-run trade and energy-demand implications. (Doha: accession protocol agreed Nov 10, 2001.)",
    description_fa: "عمیق‌شدن تولید جهانی و اثر برداشت بلندمدت روی انرژی-تقاضا.",
    category: "global",
    tags: ["trade", "china", "wto"],
    importance: 2,
  },
  {
    id: "g-2014-crimea",
    date_start: "2014-02-20",
    title_en: "Ukraine crisis: Crimea annexation phase",
    title_fa: "بحران اوکراین: فاز تثبیت/ضمیمه کریمه",
    description_en: "Escalation after Kyiv uprising; first phase of a long U.S.–EU–Russia sanctions and FX arc.",
    description_fa: "تصاعد و آغاز کمانی از تحریم-ارز غرب/روسیه.",
    category: "global",
    tags: ["russia", "europe", "sanctions"],
    importance: 3,
  },
  {
    id: "g-isis-mosul",
    date_start: "2014-06-10",
    title_en: "ISIS captures Mosul (regional war economy)",
    title_fa: "تثبیت داعش و موصل (جنگ اقتصاد منطقه‌ای)",
    description_en: "Jihadist territorial peak; large displacement and oil field contestation in Iraq context.",
    description_fa: "شاخص ارضی-امنیتی و اثر بر تولید نفت/پناهندگان.",
    category: "war",
    tags: ["iraq", "isis", "oil"],
    importance: 2,
  },
  {
    id: "g-euro-99",
    date_start: "1999-01-01",
    title_en: "Euro goes live (Phase 1–3; notes later)",
    title_fa: "راه‌اندازی یورو (فاز نخست)",
    description_en: "Monetary union currency introduced; long-run FX/anchor effects for many trading partners.",
    description_fa: "ایجاد اتحاد پولی یورو؛ اثر ماندگار فکس-شناور/حساب‌های تجاری.",
    category: "fx",
    tags: ["eur", "europe", "monetary-union"],
    importance: 2,
  },
  {
    id: "g-egypt-11",
    date_start: "2011-01-25",
    title_en: "Egypt: 25 January revolution (Tahrir)",
    title_fa: "انقلاب ۲۵ ژانویه مصر (میدان تحریر)",
    description_en: "Uprising; regional politics and oil-transit/insurance risk in Suez and wider MENA.",
    description_fa: "قدرت‌زدایی و اثر بر ریسک ممر/Suez و MENA.",
    category: "global",
    tags: ["egypt", "arab-spring", "mideast"],
    importance: 3,
  },
  {
    id: "g-japan-311",
    date_start: "2011-03-11",
    title_en: "Tohoku earthquake, tsunami, Fukushima",
    title_fa: "زلزله-سونامی توهوؤکو و فوکوشیما",
    description_en: "Catastrophe; nuclear policy shock, LNG demand shifts, and safety-driven energy transitions.",
    description_fa: "تصادم هسته‌ای-انرژی: تقاضا برای LNG و چرخش سیاستی.",
    category: "global",
    tags: ["fukushima", "lng", "japan"],
    importance: 3,
  },
  {
    id: "g-2003-iraq",
    date_start: "2003-03-20",
    title_en: "U.S.-led invasion of Iraq",
    title_fa: "حمله آمریکایی-متحد به عراق",
    description_en: "Regime change; long insurgency; structural uncertainty for Middle East oil supply.",
    description_fa: "تغییر نظام و جنگ‌های فرسایشی و ریسک عرضه میدل‌ایست.",
    category: "war",
    tags: ["iraq", "us", "mideast"],
    importance: 1,
  },
  {
    id: "g-afghan-21",
    date_start: "2021-08-15",
    title_en: "Taliban capture Kabul (U.S. exit)",
    title_fa: "تسلط طالبان بر کابل (خروج آمریکا)",
    description_en: "Sudden regime change; global refugee and security-policy revaluation.",
    description_fa: "تغییر تند نظام و بازسنجی امنیت/پناهجویی.",
    category: "war",
    tags: ["afghanistan", "taliban", "us-exit"],
    importance: 2,
  },
  {
    id: "g-2000-dot",
    date_start: "2000-03-10",
    title_en: "Dot-com index peak (Nasdaq context)",
    title_fa: "اوج حباب دات‌کام (نزدک)",
    description_en: "Illustrative anchor for post-bubble equity/USD wealth effects and venture cycle.",
    description_fa: "لنگر پساجنگ رونده سهام/واقع‌گرایی بنگاه.",
    category: "global",
    tags: ["equities", "us", "cycle"],
    importance: 1,
  },
  {
    id: "g-euro-08",
    date_start: "2008-10-10",
    title_en: "Euro area acute phase of GFC (post-Lehman)",
    title_fa: "بحران حاد منطقه یورو پس از لهمن",
    description_en: "Cross-border bank stress, sovereign risk repricing, ECB support era begins.",
    description_fa: "تنش بانکی فرامرزی و اصلاح قیمت‌گذاری ریسک حاکمیت؛ شروع دوره اقدامات BCE.",
    category: "fx",
    tags: ["europe", "ecb", "gfc"],
    importance: 2,
  },
  {
    id: "g-2010-spill",
    date_start: "2010-04-20",
    title_en: "Deepwater Horizon (Macondo) blowout",
    title_fa: "فاجعه مکوندو/دیپواتر هورایزن",
    description_en: "Gulf of Mexico oil spill; offshore regulation and liability regime shock.",
    description_fa: "ریزش-تنظیمی-مسئولیتی بخش دریایی-خلیج-مکزیکو.",
    category: "oil",
    tags: ["gulf", "safety", "us"],
    importance: 3,
  },
  {
    id: "g-syria-11",
    date_start: "2011-03-15",
    title_en: "Syria uprising begins",
    title_fa: "آغاز بحران سوریه (اعتراض/جنگ داخلی)",
    description_en: "Escalation to protracted war; large refugee flows, regional proxying, and oil-risk backdrop.",
    description_fa: "تداوم جنگ-پناهنده و پراکسی-منطقه‌ای و بک‌دراپ نفتی خاورمیانه.",
    category: "war",
    tags: ["syria", "mideast", "refugees"],
    importance: 1,
  },
  {
    id: "g-oil-negative", // illustrative (contract-specific)
    date_start: "2020-04-20",
    title_en: "WTI May 2020 contract: negative print (pandemic context)",
    title_fa: "WTI ۲۰ ماه: چاپ نزولی/منفی (زمینه ساقط کرونا)",
    description_en: "Storage/contract design stress, not a durable physical price level; use as a crisis anchor.",
    description_fa: "تنش کنت‌انگیز ذخایر-قرارداد؛ سطح ماندگار مادی نیست.",
    category: "oil",
    tags: ["wti", "pandemic", "storage"],
    importance: 1,
  },
  {
    id: "g-2023-gaza-escalation",
    date_start: "2023-10-07",
    title_en: "Gaza/Israel: major escalation (2023)",
    title_fa: "تصعید غزه/فلسطین (۲۰۲۳)",
    description_en: "Large human/security shock; MENA energy-transit, insurance, and policy responses.",
    description_fa: "تصعید امنیتی-انسانی بزرگ؛ اثر بر ریسک-ارزی-انرژی MENA (غیرنقطه‌ای-صرف).",
    category: "war",
    tags: ["gaza", "mideast", "security"],
    importance: 3,
  },
  {
    id: "ir-nuc-natanz",
    date_start: "2020-04-11",
    title_en: "Natanz: reported incident (context anchor)",
    title_fa: "نطنز: حادثه گزارش‌شده (نقطه مثال)",
    description_en: "Illustrative anchor in nuclear/centrifuge and regional-security narratives (factual details disputed).",
    description_fa: "لنگر روایتی-امنیتی در اطراف برنامه هسته‌ای/شگردهای منطقه‌ای.",
    category: "iran",
    tags: ["nuclear", "natanz", "security"],
    importance: 1,
  },
  {
    id: "ir-2019-nov",
    date_start: "2019-11-15",
    title_en: "2019 national protests (petrol price shock trigger)",
    title_fa: "اعترضات ۱۳۹۸ (آغاز با اصلاح نرخ بنزین و اعتراض ملی–سراسری)",
    description_en: "Large-scale street mobilization; internet curtailment; long macro/fiscal undercurrents.",
    description_fa: "موبیالیزه گسترده؛ اختلال نت/پسزمینه اقتصاد-پول/بنزین.",
    category: "iran",
    tags: ["2019", "protests", "prices"],
    importance: 2,
  },
  {
    id: "g-1990-reunif",
    date_start: "1990-10-03",
    title_en: "German reunification (currency/FX anchor)",
    title_fa: "وحده آلمان (لنگر ارز/ادغام)",
    description_en: "East marks converted; ECU/EU institutional backdrop; one-off FX regime shift in Europe.",
    description_fa: "تبدیل علامت شرقی؛ زیرنویس نهادهای اروپا و زیر-فیکس-شناور.",
    category: "fx",
    tags: ["europe", "dem", "euro-path"],
    importance: 1,
  },
  {
    id: "g-plaza",
    date_start: "1985-09-22",
    title_en: "Plaza Accord (USD realignment)",
    title_fa: "پیمان پلازا (بازتنظیم نسبی قدرت دلار)",
    description_en: "Coordinated G-5 plan to depreciate the dollar vs yen/DM; key FX order-of-magnitude event.",
    description_fa: "تطبیق هم‌آهنگ ۵-گانه ۱۹۸۵: فشار به ارزش واقعی دلار.",
    category: "fx",
    tags: ["g5", "jpy", "d-mark"],
    importance: 3,
  },
  {
    id: "g-ltcm",
    date_start: "1998-09-23",
    title_en: "LTCM near-failure / Fed-supervised unwinding",
    title_fa: "بحران LTCM و واداشت تحت سِمِ فدرال ریزروم",
    description_en: "Levered-arbitrage fund stress; liquidity/FICC plumbing shock with policy intervention.",
    description_fa: "تنش نقدینگی و فشار در زنجیره‌ی فاینکس/اوراق؛ سازوکار هماهنگی سیاستی برای جلوگیری از فروپاشی نقدی.",
    category: "fx",
    tags: ["ficc", "liquidity", "leverage"],
    importance: 1,
  },
  {
    id: "g-1987-b",
    date_start: "1987-10-19",
    title_en: "Black Monday (global equity rout)",
    title_fa: "دوشنبه سیاه (سقوط جهانی سهام ۱۹۸۷)",
    description_en: "Largest U.S. one-day percentage drop; portfolio-insurance/liquidity story; cross-market spillover.",
    description_fa: "رکورد افت٪-روزانه مهم؛ نقدینگی/بیمه-پُرتفو و سرایت سریع بورس‌ها.",
    category: "global",
    tags: ["equities", "crash", "liquidity"],
    importance: 1,
  },
  {
    id: "g-y2k",
    date_start: "2000-01-01",
    title_en: "Y2K rollover (software risk episode)",
    title_fa: "نقطه ۲۰۰۰ (ریسک نرم‌افزار-زمان)",
    description_en: "Preparedness mitigated many failures; still a macro calendar anchor in tech/infrastructure memory.",
    description_fa: "اگرچه اختلال سیستم‌اتیک محدود بود، اما ریسک زیرسامانه/تقویم در خاطره ماکرو ماندگار ماند.",
    category: "global",
    tags: ["y2k", "infrastructure", "it"],
    importance: 1,
  },
  {
    id: "g-paris-15",
    date_start: "2015-12-12",
    title_en: "Paris Agreement (climate framework adopted)",
    title_fa: "تصویب لایحه-چارچوب پاریس ۲۰۱۵ (اقلیم و انرژی/انتقال)",
    description_en: "UNFCCC text adopted; long-horizon signal for energy investment and transition-finance framing.",
    description_fa: "متحدالمللی‌سازی تهدید-اقتصاد-انرژی در بلند-مدت.",
    category: "global",
    tags: ["cop21", "climate", "framework"],
    importance: 3,
  },
  {
    id: "g-wto-95",
    date_start: "1995-01-01",
    title_en: "WTO establishment (GATT → WTO)",
    title_fa: "راه‌اندازگی WTO (گات→WTO) ",
    description_en: "Legal-institutional turn in world trade; dispute body and accession as macro backdrop.",
    description_fa: "نقطه‌ای که چارچوب-حقوی/حل-اختلاف-تعرفه را در تجارت-جهانی قوی‌تر کرد.",
    category: "global",
    tags: ["multilateral", "gatt", "disputes"],
    importance: 1,
  },
  ...SIGNALMAP_OIL_TIMELINE,
  ...SIGNALMAP_BALKAN_AND_WAR_RANGES,
  ...ARAB_SPRING_TIMELINE_DOT,
];
