import type { BandTimelineEvent } from "./types";

/** Swimlane order: Iran, France, UK, US, global (top to bottom in the UI). */
export const COMPARATIVE_HISTORY_LANE_ORDER = [
  "hist_iran",
  "hist_france",
  "hist_uk",
  "hist_us",
  "hist_global",
] as const;

export const COMPARATIVE_HISTORY_LAYER_UI: {
  key: (typeof COMPARATIVE_HISTORY_LANE_ORDER)[number];
  labelEn: string;
  labelFa: string;
}[] = [
  { key: "hist_iran", labelEn: "Iran", labelFa: "ایران" },
  { key: "hist_france", labelEn: "France", labelFa: "فرانسه" },
  { key: "hist_uk", labelEn: "England / UK", labelFa: "انگلیس / بریتانیا" },
  { key: "hist_us", labelEn: "United States", labelFa: "ایالات متحده" },
  { key: "hist_global", labelEn: "Global eras", labelFa: "دوره‌های جهانی" },
];

/**
 * Comparative political / cultural spans for five lanes. Dates are schematic (historical
 * periodization, not a complete atlas). BCE: leading minus on year in ISO-like strings, parsed
 * with `parseYmdToUtcMs` (e.g. `-550-01-01`).
 */
export const COMPARATIVE_HISTORY_BAND: BandTimelineEvent[] = [
  /* —— Iran —— */
  {
    kind: "period",
    id: "ch-ir-acha",
    start_date: "-550-01-01",
    end_date: "-330-01-01",
    title_en: "Achaemenid",
    title_fa: "هخامنشی",
    lane: "hist_iran",
    category: "hist_iran",
    importance: 3,
    description_en: "Achaemenid-Persian imperial state (conventional end around Alexander’s conquest of the core).",
    description_fa: "دولت امپراتوری هخامنشی (پایان نمادین با فتح‌های هسته).",
  },
  {
    kind: "period",
    id: "ch-ir-parthian",
    start_date: "-247-01-01",
    end_date: "224-01-01",
    title_en: "Parthian (Arsacid) Iran",
    title_fa: "اشکانی (پارتی)",
    lane: "hist_iran",
    category: "hist_iran",
    importance: 3,
    description_en: "Eastern Iranian–led empire, rival to Rome; gives way to the Sasanian line.",
    description_fa: "امپراتوری ایرانی-شرقی، رقیب رم؛ جایگزین: ساسانیان.",
  },
  {
    kind: "period",
    id: "ch-ir-sasanian",
    start_date: "224-01-01",
    end_date: "651-01-01",
    title_en: "Sasanian Empire",
    title_fa: "ساسانیان",
    lane: "hist_iran",
    category: "hist_iran",
    importance: 3,
    description_en: "Late-ancient Iranian high empire; fall in the 7th-century conquests (display end ~651).",
    description_fa: "دولت بزرگ ساسانی؛ سقوط در موج فتح‌های سده هفتم (نها حوالی ۶۵۱).",
  },
  {
    kind: "period",
    id: "ch-ir-medieval-early",
    start_date: "651-01-01",
    end_date: "1501-01-01",
    title_en: "Islamic & Turco-Mongol Iran (schematic)",
    title_fa: "ایران اسلامی و ترک-مغول (نمادین)",
    lane: "hist_iran",
    category: "hist_iran",
    importance: 2,
    description_en:
      "Umayyad/ʿAbbāsid through Ilkhanid and Tīmūrid / Turcoman successors—borders were fluid; one lane band for overview only.",
    description_fa: "نمای کلی: عباسی تا ایلخان و تیمور؛ مرز و دولتهای موازی در این باند تفکیک کامل نمیشود.",
  },
  {
    kind: "period",
    id: "ch-ir-safavid",
    start_date: "1501-01-01",
    end_date: "1736-01-01",
    title_en: "Safavid Iran",
    title_fa: "صفویه",
    lane: "hist_iran",
    category: "hist_iran",
    importance: 3,
    description_en: "Strong centre and Twelver Shīʿa state; major early-modern art and trade.",
    description_fa: "تمرکز و تثبیت مذهب شیعه دوازدهامامی و درخشش فرهنگی-تجاری.",
  },
  {
    kind: "period",
    id: "ch-ir-qajar",
    start_date: "1794-01-01",
    end_date: "1925-01-01",
    title_en: "Qajar",
    title_fa: "قاجار",
    lane: "hist_iran",
    category: "hist_iran",
    importance: 3,
    description_en: "19th–early 20th century; constitutionalism, oil, and the First World War context.",
    description_fa: "سده نوزدهم و آغاز بیستم؛ مشروطه، نفت و جنگ جهانی.",
  },
  {
    kind: "period",
    id: "ch-ir-pahlavi",
    start_date: "1925-01-01",
    end_date: "1979-01-01",
    title_en: "Pahlavi",
    title_fa: "پهلوی",
    lane: "hist_iran",
    category: "hist_iran",
    importance: 3,
    description_en: "Authoritarian modernisation and the 1979 revolution that ends the monarchy.",
    description_fa: "مدرنیزاسیون متراکم و انجام انقلاب ۱۳۵۷.",
  },
  {
    kind: "period",
    id: "ch-ir-iri",
    start_date: "1979-01-01",
    end_date: "2030-12-31",
    title_en: "Islamic Republic of Iran",
    title_fa: "جمهوری اسلامی ایران",
    lane: "hist_iran",
    category: "hist_iran",
    importance: 3,
    description_en: "Republican order after 1979; end date is a display window only.",
    description_fa: "نظام پس از ۱۳۵۷؛ پایان فقط برای مکاننمای نمایش است.",
  },
  /* —— France —— */
  {
    kind: "period",
    id: "ch-fr-medieval",
    start_date: "987-01-01",
    end_date: "1589-01-01",
    title_en: "Medieval Capetian / Valois (schematic)",
    title_fa: "قرون وسطی کاپِتی / والوا (نمادین)",
    lane: "hist_france",
    category: "hist_france",
    importance: 2,
    description_en: "Kings of France: Capetian to Valois, before the Bourbon high monarchy; schematic span.",
    description_fa: "نمای کلی از لوییها تا پایان ولوا (تفکیک کامل داخلی نه).",
  },
  {
    kind: "period",
    id: "ch-fr-bourbon-ancient",
    start_date: "1589-01-01",
    end_date: "1789-07-14",
    title_en: "Bourbon (Ancien Régime)",
    title_fa: "بوربون (رژیم قدیم)",
    lane: "hist_france",
    category: "hist_france",
    importance: 2,
    description_en: "Centralised Bourbon monarchy until the 1789 Revolution.",
    description_fa: "تمرکز سلطنت بوربون تا انقلا ۱۷۸۹.",
  },
  {
    kind: "period",
    id: "ch-fr-revolution",
    start_date: "1789-01-01",
    end_date: "1799-11-10",
    title_en: "French Revolution",
    title_fa: "انقلاب فرانسه",
    lane: "hist_france",
    category: "hist_france",
    importance: 3,
    description_en: "Overthrow of the old regime and the revolutionary decade.",
    description_fa: "سقوط رژیم قدیم و دهه انقلابی.",
  },
  {
    kind: "period",
    id: "ch-fr-napoleon",
    start_date: "1799-11-10",
    end_date: "1815-07-15",
    title_en: "Consulate & Napoleonic Empire",
    title_fa: "کونسولگاری و امپراتوری ناپلئون",
    lane: "hist_france",
    category: "hist_france",
    importance: 3,
    description_en: "Napoléon’s consulate, empire, and defeat (Waterloo; restoration follows).",
    description_fa: "کونسول، امپراتوری و شکست؛ بازگشت بوربن.",
  },
  {
    kind: "period",
    id: "ch-fr-1815-48",
    start_date: "1814-01-01",
    end_date: "1848-01-01",
    title_en: "Restoration & July Monarchy",
    title_fa: "بازگشتیان و جولی",
    lane: "hist_france",
    category: "hist_france",
    importance: 2,
    description_en: "Bourbon restoration, then 1830 July Monarchy, until 1848 upheavals.",
    description_fa: "دوره بازسازی بوربن و سپس سلطنت جولی تا انقلا ۱۸۴۸.",
  },
  {
    kind: "period",
    id: "ch-fr-second-empire",
    start_date: "1852-01-01",
    end_date: "1870-09-04",
    title_en: "Second Empire",
    title_fa: "دومین امپراتوری",
    lane: "hist_france",
    category: "hist_france",
    importance: 2,
    description_en: "Napoléon III; ends with the defeat at Sedan 1870.",
    description_fa: "ناپلئون سوم؛ پایان با سدان ۱۸۷۰.",
  },
  {
    kind: "period",
    id: "ch-fr-third",
    start_date: "1870-01-01",
    end_date: "1940-07-10",
    title_en: "Third Republic",
    title_fa: "سومین جمهوری",
    lane: "hist_france",
    category: "hist_france",
    importance: 2,
    description_en: "Parliamentary republic, WWI, and interwar period until the 1940 fall of France.",
    description_fa: "جمهوری پارلمانی، جنگجهانی اول و بینالجنگ تا سقوط ۱۹۴۰.",
  },
  {
    kind: "period",
    id: "ch-fr-ww2",
    start_date: "1940-01-01",
    end_date: "1944-12-01",
    title_en: "Vichy & liberation",
    title_fa: "ویشی و آزادی",
    lane: "hist_france",
    category: "hist_france",
    importance: 2,
    description_en: "Pétain regime, occupation, and Resistance context (schematic block).",
    description_fa: "رژیم پتن، اشغال و مقاومت (باند کلی).",
  },
  {
    kind: "period",
    id: "ch-fr-4th-5th",
    start_date: "1946-01-01",
    end_date: "2026-12-31",
    title_en: "Fourth & Fifth Republics",
    title_fa: "جمهوری چهارم و پنجم",
    lane: "hist_france",
    category: "hist_france",
    importance: 2,
    description_en: "Post-WW2 Fourth Republic, then 1958 Fifth Republic; display end is a rolling year.",
    description_fa: "جمهوری چهارم پس از جنگ و پنجم از ۱۹۵۸؛ پایان نمادین.",
  },
  /* —— England / UK —— */
  {
    kind: "period",
    id: "ch-uk-plantagenet",
    start_date: "1066-01-01",
    end_date: "1485-08-22",
    title_en: "Norman to Plantagenet / Wars of the Roses (schematic)",
    title_fa: "نرماند تا پلانتاژنه (نمادین)",
    lane: "hist_uk",
    category: "hist_uk",
    importance: 2,
    description_en: "Conquest, Plantagenet kings, and the late civil wars; schematic one band for overview.",
    description_fa: "فتح، پادشاهی پلانتاژن و نبرد رزها (یک باند کلی).",
  },
  {
    kind: "period",
    id: "ch-uk-tudor",
    start_date: "1485-01-01",
    end_date: "1603-01-01",
    title_en: "Tudor",
    title_fa: "تودور",
    lane: "hist_uk",
    category: "hist_uk",
    importance: 3,
    description_en: "Tudor monarchy and the English Reformation.",
    description_fa: "سلاله تودور و اصلاحات مذهبی انگلیس.",
  },
  {
    kind: "period",
    id: "ch-uk-stuart",
    start_date: "1603-01-01",
    end_date: "1714-01-01",
    title_en: "Stuart",
    title_fa: "استوارت",
    lane: "hist_uk",
    category: "hist_uk",
    importance: 2,
    description_en: "Civil war, interregnum, and Glorious Revolution transition.",
    description_fa: "جنگداخلی، عصر کمون و انقلاب باشکوه.",
  },
  {
    kind: "period",
    id: "ch-uk-georgian",
    start_date: "1714-01-01",
    end_date: "1837-01-01",
    title_en: "Georgian Britain",
    title_fa: "دوره ژرجی",
    lane: "hist_uk",
    category: "hist_uk",
    importance: 2,
    description_en: "Hanoverian (Georgian) monarchy, empire building, and industrial start.",
    description_fa: "هانوفر (ژرج)، امپراتوری و آغاز صنعت.",
  },
  {
    kind: "period",
    id: "ch-uk-victorian",
    start_date: "1837-01-01",
    end_date: "1901-01-22",
    title_en: "Victorian",
    title_fa: "ویکتوریا",
    lane: "hist_uk",
    category: "hist_uk",
    importance: 3,
    description_en: "Height of the British industrial empire; Pax Britannica imagery.",
    description_fa: "اوج امپراتوری صنعتی و ایده بریتانیا کبیر.",
  },
  {
    kind: "period",
    id: "ch-uk-edwardian-mod",
    start_date: "1901-01-22",
    end_date: "2026-12-31",
    title_en: "Edwardian, world wars, modern UK",
    title_fa: "ادوارد و جنگها و بریتانیا نوین",
    lane: "hist_uk",
    category: "hist_uk",
    importance: 2,
    description_en: "From Edward VII through the world wars, decolonisation, to the current United Kingdom; display end is a stub year.",
    description_fa: "ادوارد، جنگهایجهانی، پساساستعمار تا امروز (پایان نمادین).",
  },
  /* —— United States —— */
  {
    kind: "period",
    id: "ch-us-colonial",
    start_date: "1607-01-01",
    end_date: "1776-07-04",
    title_en: "Colonial & British America",
    title_fa: "استعمار و آمریکای بریتانیا",
    lane: "hist_us",
    category: "hist_us",
    importance: 2,
    description_en: "Jamestown through independence.",
    description_fa: "جیمزتاون تا استقلال.",
  },
  {
    kind: "period",
    id: "ch-us-rev-early",
    start_date: "1765-01-01",
    end_date: "1815-01-01",
    title_en: "Revolution & early republic",
    title_fa: "انقلاب و جمهوری نخست",
    lane: "hist_us",
    category: "hist_us",
    importance: 3,
    description_en: "Crisis with Britain, 1776, Constitution, 1812 war, and the early federal era.",
    description_fa: "بحران با بریتانیا، ۱۷۷۶، قانون اساسی و دوره فدرال نخست.",
  },
  {
    kind: "period",
    id: "ch-us-1815-61",
    start_date: "1815-01-01",
    end_date: "1860-12-31",
    title_en: "Antebellum expansion",
    title_fa: "توسعه پیشاجنگ داخلی",
    lane: "hist_us",
    category: "hist_us",
    importance: 2,
    description_en: "Westward growth and sectional stress before the Civil War.",
    description_fa: "رشد غرب و تنش اتحادیه-استانها.",
  },
  {
    kind: "period",
    id: "ch-us-civil",
    start_date: "1861-01-01",
    end_date: "1877-01-01",
    title_en: "Civil War & Reconstruction",
    title_fa: "جنگداخلی و بازسازی",
    lane: "hist_us",
    category: "hist_us",
    importance: 3,
    description_en: "Civil war and federal reconstruction; schematic end 1877.",
    description_fa: "جنگ اتحاديه و يالها و ريكونستركشن (پایان نمادین ۱۸۷۷).",
  },
  {
    kind: "period",
    id: "ch-us-gilded",
    start_date: "1877-01-01",
    end_date: "1900-01-01",
    title_en: "Gilded Age",
    title_fa: "عصر زرین",
    lane: "hist_us",
    category: "hist_us",
    importance: 2,
    description_en: "Industrialization, robber-baron iconography, and Gilded Age politics.",
    description_fa: "صنعت، وصلای امپراتورها و سیاست دوره «طلایی».",
  },
  {
    kind: "period",
    id: "ch-us-progressive",
    start_date: "1900-01-01",
    end_date: "1929-10-24",
    title_en: "Progressive Era to crash",
    title_fa: "دوره ترقیخواهی تا رکود",
    lane: "hist_us",
    category: "hist_us",
    importance: 2,
    description_en: "Progressive reforms, World War I U.S. entry, interwar to 1929 stock crash.",
    description_fa: "برنامههای ترقیخواه، ورود به WWI و دهه اول بیستم تا ۱۹۲۹.",
  },
  {
    kind: "period",
    id: "ch-us-new-deal",
    start_date: "1929-01-01",
    end_date: "1945-09-02",
    title_en: "New Deal & World War II",
    title_fa: "دیل نوین و جنگ دوم",
    lane: "hist_us",
    category: "hist_us",
    importance: 3,
    description_en: "Depression, New Deal state-building, and U.S. role in WWII (display end V-J Day 1945).",
    description_fa: "رکود بزرگ، بساط دولت نو و نقش US درWWII (پایان ۱۹۴۵).",
  },
  {
    kind: "period",
    id: "ch-us-cold",
    start_date: "1945-01-01",
    end_date: "1991-12-26",
    title_en: "Cold War U.S.",
    title_fa: "آمریکای دوران جنگسرد",
    lane: "hist_us",
    category: "hist_us",
    importance: 3,
    description_en: "Bipolar competition, hot wars in Korea and Vietnam, détente, and Soviet collapse.",
    description_fa: "رقابت بلوکها، منازعات گرم، دیتانت و سقوط شوروی (نماد).",
  },
  {
    kind: "period",
    id: "ch-us-post911",
    start_date: "1991-12-27",
    end_date: "2026-12-31",
    title_en: "Post–Cold War / modern U.S. (schematic)",
    title_fa: "پساجنگسرد / مدرن (نمادین)",
    lane: "hist_us",
    category: "hist_us",
    importance: 2,
    description_en: "Unipolar moment, 9/11, Middle East engagement, to present—display year is a stub.",
    description_fa: "یکقطبی، ۱۱ سپتامبر و بحرانخاورمیانه تا امروز (پایان کلی).",
  },
  /* —— Global eras —— */
  {
    kind: "period",
    id: "ch-g-renaissance",
    start_date: "1300-01-01",
    end_date: "1600-12-31",
    title_en: "Renaissance",
    title_fa: "رنسانس",
    lane: "hist_global",
    category: "hist_global",
    importance: 2,
    description_en: "Literary, artistic, and early scientific revival; conventional span ~1300–1600.",
    description_fa: "نوسازی ادبی-هنری-علمی (حدود ۱۳۰۰-۱۶۰۰ میلادی).",
  },
  {
    kind: "period",
    id: "ch-g-sci-rev",
    start_date: "1543-01-01",
    end_date: "1687-12-31",
    title_en: "Scientific Revolution (schematic)",
    title_fa: "انقلاب علمی (نمادین)",
    lane: "hist_global",
    category: "hist_global",
    importance: 2,
    description_en: "Copernicus-to-Newton style narrative of early modern mathematised natural philosophy.",
    description_fa: "نمای کپرنیک-نیوتن از علم نوین (باند کلی).",
  },
  {
    kind: "period",
    id: "ch-g-enlighten",
    start_date: "1680-01-01",
    end_date: "1800-12-31",
    title_en: "Enlightenment (schematic)",
    title_fa: "تنویر (نمادین)",
    lane: "hist_global",
    category: "hist_global",
    importance: 2,
    description_en: "Luminaries, public reason, and transatlantic reform ideas before age-of-revolutions crescendos.",
    description_fa: "عقلانیت عمومی و ایده اصلاح پیش از امواج انقلا ۱۷۶۰-۱۸۵۰.",
  },
  {
    kind: "period",
    id: "ch-g-age-rev",
    start_date: "1765-01-01",
    end_date: "1849-12-31",
    title_en: "Age of Revolutions (schematic)",
    title_fa: "دوره انقلا ۱۷۶۵-۱۸۴۹ (نمادین)",
    lane: "hist_global",
    category: "hist_global",
    importance: 2,
    description_en: "Atlantic, Latin American, and 1848 wave; schematic one band, not a single event.",
    description_fa: "موج انقلا اطلس و اروپا و ۱۸۴۸ (یک باند کلی).",
  },
  {
    kind: "period",
    id: "ch-g-industry",
    start_date: "1760-01-01",
    end_date: "1840-12-31",
    title_en: "Industrial Revolution (first, schematic)",
    title_fa: "انقلاب صنعتی (نمادین)",
    lane: "hist_global",
    category: "hist_global",
    importance: 2,
    description_en: "Mechanisation and factory organisation—Britain-centred, overlapping other bands.",
    description_fa: "مکانیزهسازی (مرکز غالب بریتانیا) و همپوشانی سایر باندهای زمانی.",
  },
  {
    kind: "period",
    id: "ch-g-ww1",
    start_date: "1914-07-28",
    end_date: "1918-11-11",
    title_en: "World War I",
    title_fa: "جنگجهانی اول",
    lane: "hist_global",
    category: "hist_global",
    importance: 3,
    description_en: "Great War in Europe, empires, and 1918 armistice line.",
    description_fa: "بزرگ ۱۹۱۴-۱۹۱۸؛ پایان با آتشبس.",
  },
  {
    kind: "period",
    id: "ch-g-ww2",
    start_date: "1939-09-01",
    end_date: "1945-09-02",
    title_en: "World War II",
    title_fa: "جنگجهانی دوم",
    lane: "hist_global",
    category: "hist_global",
    importance: 3,
    description_en: "Global war, Holocaust, and atom bomb context; 1945 surrender dates vary by theatre.",
    description_fa: "بحران جهانگیر؛ تاریخهای تسلیم ۱۹۴۵ متفاوت است.",
  },
  {
    kind: "period",
    id: "ch-g-cold",
    start_date: "1947-01-01",
    end_date: "1991-12-26",
    title_en: "Cold War",
    title_fa: "جنگسرد",
    lane: "hist_global",
    category: "hist_global",
    importance: 3,
    description_en: "Bipolar competition; conventional end 1991 Soviet dissolution (display).",
    description_fa: "رقابت دو بلوک؛ نها نمادین: فروپاشی ۱۹۹۱ شوروی.",
  },
];
