import type { BandTimelinePeriodEvent } from "./types";

/**
 * Political leadership as period bands. Term dates: Britannica, respective official offices, and
 * standard inauguration chronologies (U.S.); IRI presidency chronology (Iran).
 * Display-only: refine against primary sources for production datasets.
 */
export const LEADERSHIP_BAND_US: readonly BandTimelinePeriodEvent[] = [
  {
    kind: "period",
    id: "us-woodrow-wilson",
    start_date: "1913-03-04",
    end_date: "1921-03-04",
    title_en: "Woodrow Wilson (President)",
    title_fa: "وودرو ویلسون (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "First World War; League of Nations push; 1913–1921 (March 4 inaugurations, pre-20th Amendment).",
    description_fa: "جنگ جهانی اول؛ اتحادیه ملل؛ ۱۹۱۳–۱۹۲۱.",
    tags: ["president", "us"],
    source_citation_en: "4 Mar 1913 – 4 Mar 1921 (U.S. inaugural chronology, Britannica / NARA).",
    source_citation_fa: "۴ مارس ۱۹۱۳ – ۴ مارس ۱۹۲۱.",
  },
  {
    kind: "period",
    id: "us-warren-harding",
    start_date: "1921-03-04",
    end_date: "1923-08-02",
    title_en: "Warren G. Harding (President)",
    title_fa: "وارن جی. هاردینگ (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "Term cut short; March 4 inaugurations; ends with death 2 Aug 1923 (standard U.S. record).",
    description_fa: "دوره کوتاه، پایان به علت فوت ۱۹۲۳.",
    tags: ["president", "us"],
    source_citation_en: "4 Mar 1921 – 2 Aug 1923 (Britannica / White House).",
    source_citation_fa: "۴ مارس ۱۹۲۱ – ۲ اوت ۱۹۲۳.",
  },
  {
    kind: "period",
    id: "us-calvin-coolidge",
    start_date: "1923-08-02",
    end_date: "1929-03-04",
    title_en: "Calvin Coolidge (President)",
    title_fa: "کلوین کولیج (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "Succeeds Harding; one full term after 1924 election; pro-business “Coolidge era”.",
    description_fa: "پس از هاردینگ؛ میانهٔ رونق اقتصادی.",
    tags: ["president", "us"],
    source_citation_en: "2 Aug 1923 – 4 Mar 1929 (U.S. presidency, Britannica).",
    source_citation_fa: "۲ اوت ۱۹۲۳ – ۴ مارس ۱۹۲۹.",
  },
  {
    kind: "period",
    id: "us-herbert-hoover",
    start_date: "1929-03-04",
    end_date: "1933-03-04",
    title_en: "Herbert Hoover (President)",
    title_fa: "هربرت هوور (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "Late 1920s/early 1930s; great depression onset; single term 1929–1933 (March 4).",
    description_fa: "دوره رکود بزرگ، یک دوره ۱۹۲۹–۱۹۳۳.",
    tags: ["president", "us"],
    source_citation_en: "4 Mar 1929 – 4 Mar 1933 (Britannica / standard inaugural listing).",
    source_citation_fa: "۴ مارس ۱۹۲۹ – ۴ مارس ۱۹۳۳.",
  },
  {
    kind: "period",
    id: "us-franklin-roosevelt",
    start_date: "1933-03-04",
    end_date: "1945-04-12",
    title_en: "Franklin D. Roosevelt (President)",
    title_fa: "فرانکلین دی. رزولت (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "New Deal, Second World War; four terms, ends with death; term ends 12 Apr 1945 (standard U.S. record).",
    description_fa: "رزولت؛ جنگ جهانی دوم و نیودیل؛ پایان با فوت ۱۲ آوریل ۱۹۴۵.",
    tags: ["president", "us"],
    source_citation_en: "4 Mar 1933 – 12 Apr 1945 (FDR, Britannica / NARA; fourth term 20 Jan 1945–12 Apr 1945).",
    source_citation_fa: "۴ مارس ۱۹۳۳ (شروع) تا ۱۲ آوریل ۱۹۴۵ (پایان با فوت).",
  },
  {
    kind: "period",
    id: "us-harry-truman",
    start_date: "1945-04-12",
    end_date: "1953-01-20",
    title_en: "Harry S. Truman (President)",
    title_fa: "هری اس. ترومن (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "U.S. president from succession after Franklin D. Roosevelt; second term 1949–1953; Korean War and post-war order; term dates from standard U.S. presidency chronology (Britannica, White House historical data).",
    description_fa: "رئیس‌جمهور پس از روسوولت؛ دورهٔ دوم ۱۹۴۹–۱۹۵۳؛ جنگ کره و نظم پس‌ازجنگ؛ طبق تداول پذیرفته‌ شدهٔ سمت ریاست‌جمهوری ایالات متحده.",
    tags: ["president", "us"],
    source_citation_en: "Term range: U.S. presidency & Britannica chronology (Truman: 12 Apr 1945 – 20 Jan 1953).",
    source_citation_fa: "بازه: گاه‌شمار ریاست جمهوری؛ منابع مانند بریتانیکا/White House (ترومن: ۱۲ آوریل ۱۹۴۵ تا ۲۰ ژانویه ۱۹۵۳).",
  },
  {
    kind: "period",
    id: "us-dwight-eisenhower",
    start_date: "1953-01-20",
    end_date: "1961-01-20",
    title_en: "Dwight D. Eisenhower (President)",
    title_fa: "دوایت دی. آیزنهاور (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "Two full terms: Cold War positioning, infrastructure and defence posture; terms per standard U.S. inauguration record.",
    description_fa: "دو دوره کامل؛ جنگ سرد و زیرساخت؛ گاه‌شمار ریاست‌جمهوری.",
    tags: ["president", "us"],
    source_citation_en: "Term: 20 Jan 1953 – 20 Jan 1961 (U.S. presidency; Britannica / standard inaugural listing).",
    source_citation_fa: "۲۰ ژانویه ۱۹۵۳ – ۲۰ ژانویه ۱۹۶۱ (منبع: گاه‌شمار رسمی/بریتانیکا).",
  },
  {
    kind: "period",
    id: "us-john-kennedy",
    start_date: "1961-01-20",
    end_date: "1963-11-22",
    title_en: "John F. Kennedy (President)",
    title_fa: "جان اف. کندی (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "Term ended 22 November 1963; dates per standard U.S. historical record.",
    description_fa: "پایان دوره ۲۲ نوامبر ۱۹۶۳ طبق گاه‌شمار تاریخی پذیرفته‌شده.",
    tags: ["president", "us"],
    source_citation_en: "Term: 20 Jan 1961 – 22 Nov 1963 (U.S. presidency, Britannica / public record).",
    source_citation_fa: "۲۰ ژانویه ۱۹۶۱ – ۲۲ نوامبر ۱۹۶۳.",
  },
  {
    kind: "period",
    id: "us-lyndon-johnson",
    start_date: "1963-11-22",
    end_date: "1969-01-20",
    title_en: "Lyndon B. Johnson (President)",
    title_fa: "لیندون بی. جانسون (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "Succeeds JFK, elected full term 1964; Great Society; Vietnam era.",
    description_fa: "جانشینی پس از کندی؛ دوره کامل ۱۹۶۴.",
    tags: ["president", "us"],
    source_citation_en: "22 Nov 1963 – 20 Jan 1969 (succession; standard inaugural dates).",
    source_citation_fa: "۲۲ نوامبر ۱۹۶۳ – ۲۰ ژانویه ۱۹۶۹.",
  },
  {
    kind: "period",
    id: "us-richard-nixon",
    start_date: "1969-01-20",
    end_date: "1974-08-09",
    title_en: "Richard Nixon (President)",
    title_fa: "ریچارد نیکسون (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "Resigned 9 Aug 1974; term dates from standard U.S. record.",
    description_fa: "استعفا ۹ اوت ۱۹۷۴.",
    tags: ["president", "us"],
    source_citation_en: "20 Jan 1969 – 9 Aug 1974 (White House; Britannica).",
    source_citation_fa: "۲۰ ژانویه ۱۹۶۹ – ۹ اوت ۱۹۷۴.",
  },
  {
    kind: "period",
    id: "us-gerald-ford",
    start_date: "1974-08-09",
    end_date: "1977-01-20",
    title_en: "Gerald Ford (President)",
    title_fa: "جرالد فورد (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "Succeeds Nixon, completes term to Jan 1977.",
    description_fa: "جانشین نیکسون تا ۱۹۷۷.",
    tags: ["president", "us"],
    source_citation_en: "9 Aug 1974 – 20 Jan 1977 (Britannica / U.S. presidency).",
    source_citation_fa: "۹ اوت ۱۹۷۴ – ۲۰ ژانویه ۱۹۷۷.",
  },
  {
    kind: "period",
    id: "us-jimmy-carter",
    start_date: "1977-01-20",
    end_date: "1981-01-20",
    title_en: "Jimmy Carter (President)",
    title_fa: "جیمی کارتر (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "One term, late Cold War, Iran hostage crisis; standard inaugural dates.",
    description_fa: "یک دوره، اواخر جنگ سرد.",
    tags: ["president", "us"],
    source_citation_en: "20 Jan 1977 – 20 Jan 1981.",
    source_citation_fa: "۲۰ ژانویه ۱۹۷۷ – ۲۰ ژانویه ۱۹۸۱.",
  },
  {
    kind: "period",
    id: "us-ronald-reagan",
    start_date: "1981-01-20",
    end_date: "1989-01-20",
    title_en: "Ronald Reagan (President)",
    title_fa: "رونالد ریگان (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "Two terms, renewed conservative domestic and foreign policy.",
    description_fa: "دو دوره، محافظه‌کاری و سیاست خارجی تازه.",
    tags: ["president", "us"],
    source_citation_en: "20 Jan 1981 – 20 Jan 1989.",
    source_citation_fa: "۲۰ ژانویه ۱۹۸۱ – ۲۰ ژانویه ۱۹۸۹.",
  },
  {
    kind: "period",
    id: "us-ghw-bush",
    start_date: "1989-01-20",
    end_date: "1993-01-20",
    title_en: "George H. W. Bush (President)",
    title_fa: "جرج اچ. دبلیو. بوش (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "Gulf War era, end of Cold War; one term per standard record.",
    description_fa: "دوره جنگ خلیج فارس، پایان مرحله‌ای از جنگ سرد.",
    tags: ["president", "us"],
    source_citation_en: "20 Jan 1989 – 20 Jan 1993.",
    source_citation_fa: "۲۰ ژانویه ۱۹۸۹ – ۲۰ ژانویه ۱۹۹۳.",
  },
  {
    kind: "period",
    id: "us-bill-clinton",
    start_date: "1993-01-20",
    end_date: "2001-01-20",
    title_en: "Bill Clinton (President)",
    title_fa: "بیل کلینتون (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "Two full terms, post–Cold War economy and multilateral order.",
    description_fa: "دو دوره، اقتصاد و نظم بین‌الملل پس از جنگ سرد.",
    tags: ["president", "us"],
    source_citation_en: "20 Jan 1993 – 20 Jan 2001.",
    source_citation_fa: "۲۰ ژانویه ۱۹۹۳ – ۲۰ ژانویه ۲۰۰۱.",
  },
  {
    kind: "period",
    id: "us-gw-bush",
    start_date: "2001-01-20",
    end_date: "2009-01-20",
    title_en: "George W. Bush (President)",
    title_fa: "جرج دبلیو. بوش (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "9/11, Afghanistan and Iraq wars, financial crisis late term.",
    description_fa: "یازده سپتامبر، افغانستان و عراق و بحران مالی پایان دوره.",
    tags: ["president", "us"],
    source_citation_en: "20 Jan 2001 – 20 Jan 2009.",
    source_citation_fa: "۲۰ ژانویه ۲۰۰۱ – ۲۰ ژانویه ۲۰۰۹.",
  },
  {
    kind: "period",
    id: "us-barack-obama",
    start_date: "2009-01-20",
    end_date: "2017-01-20",
    title_en: "Barack Obama (President)",
    title_fa: "باراک اوباما (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "Two terms, recovery from 2008 crisis, health reform, Middle East rebalancing.",
    description_fa: "دو دوره، بهبود پس از ۲۰۰۸ و اصلاح سلامت.",
    tags: ["president", "us"],
    source_citation_en: "20 Jan 2009 – 20 Jan 2017.",
    source_citation_fa: "۲۰ ژانویه ۲۰۰۹ – ۲۰ ژانویه ۲۰۱۷.",
  },
  {
    kind: "period",
    id: "us-donald-trump-1",
    start_date: "2017-01-20",
    end_date: "2021-01-20",
    title_en: "Donald J. Trump (President, first term)",
    title_fa: "دونالد جی. ترامپ (رئیس‌جمهور، دوره نخست)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "First term, first presidency (non-consecutive second term from 2025 in separate band).",
    description_fa: "دوره نخست؛ دوره دوم جدا (از ۲۰۲۵) در باند جدا.",
    tags: ["president", "us"],
    source_citation_en: "20 Jan 2017 – 20 Jan 2021 (first term, standard inaugural dates).",
    source_citation_fa: "۲۰ ژانویه ۲۰۱۷ – ۲۰ ژانویه ۲۰۲۱ (دوره نخست).",
  },
  {
    kind: "period",
    id: "us-joe-biden",
    start_date: "2021-01-20",
    end_date: "2025-01-20",
    title_en: "Joe Biden (President)",
    title_fa: "جو بایدن (رئیس‌جمهور)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "One term, COVID-19, Ukraine, Middle East; term end per 2025 inaugural cycle.",
    description_fa: "کووید، اوکراین، خاورمیانه؛ پایان ۲۰۲۵ در چرخه استقرار ریاست‌جمهوری جدید.",
    tags: ["president", "us"],
    source_citation_en: "20 Jan 2021 – 20 Jan 2025 (U.S. presidency, Britannica / White House).",
    source_citation_fa: "۲۰ ژانویه ۲۰۲۱ – ۲۰ ژانویه ۲۰۲۵.",
  },
  {
    kind: "period",
    id: "us-donald-trump-2",
    start_date: "2025-01-20",
    end_date: "2029-01-20",
    title_en: "Donald J. Trump (President, second term)",
    title_fa: "دونالد جی. ترامپ (رئیس‌جمهور، دوره دوم)",
    lane: "us_leadership",
    category: "us_leadership",
    importance: 3,
    description_en: "Second, non-consecutive term; end date is nominal second term window (4-year cycle).",
    description_fa: "دوره دوم غیرپیوسته؛ پایان تقریبی چرخه ۴ساله.",
    tags: ["president", "us"],
    source_citation_en: "Second term from 20 Jan 2025; end shown as nominal second full term; verify against official U.S. record.",
    source_citation_fa: "دوره دوم از ۲۰ ژانویه ۲۰۲۵؛ پایان تقریبی؛ هنگام داده تولیدی با سند رسمی تطبیق داده شود.",
  },
];

export const LEADERSHIP_BAND_IR: readonly BandTimelinePeriodEvent[] = [
  {
    kind: "period",
    id: "ir-ahmad-shah-qajar",
    start_date: "1914-07-28",
    end_date: "1925-10-30",
    title_en: "Ahmad Shah Qajar (Shah of Iran)",
    title_fa: "احمدشاه قاجار (شاه ایران)",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 2,
    description_en:
      "Late Qajar monarchy; band starts with the band-timeline window (1914) for continuity; ends before the Pahlavi accession. Full reign 1909–1925 (refine for production).",
    description_fa:
      "پایان عصر قاجار در این داده از ۱۹۱۴ شروع و تا قبل از ۱۳۰۴ ادامه دارد؛ پادشاهی کامل ۱۲۸۸–۱۳۰۴ (با منبع نهایی تطبیق دهید).",
    tags: ["qajar", "monarchy", "iran"],
    source_citation_en: "Qajar end of reign ~Oct 1925; display band aligned to chart domain from Jul 1914 (WWI anchor in seed).",
    source_citation_fa: "پایان ۱۳۰۴؛ نمایش از ۱۹۱۴ با دامنهٔ باند تطبیق داده شده.",
  },
  {
    kind: "period",
    id: "ir-reza-khan-executive-1923",
    start_date: "1923-10-28",
    end_date: "1925-10-30",
    title_en: "Reza Khan (PM / effective government)",
    title_fa: "رضاخان (نخست‌وزیری / اقتدار موثر)",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 2,
    description_en:
      "As Sardar Sepah, then Prime Minister, Reza holds effective power over the Qajar monarchy; overlaps late Ahmad Shah’s nominal rule; he became Shah in Dec 1925 in the same consolidation arc.",
    description_fa:
      "نخست‌وزیر و اقتدار عملی پادشاهی ضعیف‌شدهٔ قاجار (هم‌پوشانی با احمدشاه)؛ تاج‌گذاری ۱۳۰۴ گام بعدی همان بسط قدرت است.",
    tags: ["pahlavi", "reza-shah", "monarchy", "iran"],
    source_citation_en: "PM/executive phase; dates rounded to standard chronology (e.g. Britannica / IRI); refine with official gazette.",
    source_citation_fa: "نوبت اجرائی؛ مبنا گاه‌شمار پذیرفته‌شده؛ اصلاح با سند.",
  },
  {
    kind: "period",
    id: "ir-reza-shah-pahlavi",
    start_date: "1925-10-31",
    end_date: "1941-09-16",
    title_en: "Reza Shah Pahlavi (Shah of Iran)",
    title_fa: "رضا شاه پهلوی (شاه ایران)",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 3,
    description_en: "Pahlavi dynasty as Shah; forced abdication Sept 1941; successor is Mohammad Reza Pahlavi from 16 Sept 1941 (standard chronology).",
    description_fa: "شاهنشاهی پهلوی؛ اجبار به ترک ۱۳۲۰؛ ادامه با محمدرضا از ۲۵ شهریور ۱۳۲۰.",
    tags: ["pahlavi", "reza-shah", "monarchy", "iran"],
    source_citation_en: "Shah from late 1925; abdication 16 Sept 1941; Britannica / standard Iranian modern history chronology.",
    source_citation_fa: "از ۱۳۰۴ به‌عنوان شاه؛ استعفای اجباری ۲۵ شهریور ۱۳۲۰.",
  },
  {
    kind: "period",
    id: "ir-mrshah-pahlavi-period",
    start_date: "1941-09-16",
    end_date: "1979-02-11",
    title_en: "Mohammad Reza Pahlavi (Shah) — Pahlavi monarchy",
    title_fa: "محمدرضا پهلوی (شاه) — دوره پادشاهی",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 3,
    description_en: "Reign of the last Shah from succession (Sept 1941) to the 1979 revolution; modernisation and then crisis.",
    description_fa: "آخرین شاه از جانشینی ۱۳۲۰ تا ۵۷؛ اصلاح و سپس بحران ۱۳۵۷.",
    tags: ["pahlavi", "monarchy", "iran", "reza-pahlavi-era"],
    source_citation_en: "From Shah’s accession after Reza Shah’s forced abdication (16 Sept 1941) to revolution end (11 Feb 1979); use official chronology for sub-month precision.",
    source_citation_fa: "از ۲۵ شهریور ۱۳۲۰ تا ۲۲ بهمن ۱۳۵۷ (تقویم رسمی-تفسیری برای نمایش).",
  },
  {
    kind: "period",
    id: "ir-bazargan",
    start_date: "1979-02-12",
    end_date: "1979-11-05",
    title_en: "Mehdi Bazargan (Interim Government, Prime Minister)",
    title_fa: "مهدی بازرگان (دولت موقت، نخست‌وزیر)",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 3,
    description_en:
      "Provisional government after the 1979 revolution; Bazargan leads until resignation after the U.S. embassy episode (rough window; end date rounded in seed).",
    description_fa:
      "ریاست دولت موقت پس از انقلاب ۱۳۵۷ تا دوره پایان با استعفا/بحران سفارت (بازه تقریبی؛ اصلاح با سند).",
    tags: ["provisional", "iran", "revolution"],
    source_citation_en: "Bazargan as PM, interim; verify exact mandate end against official IRI/standard histories.",
    source_citation_fa: "نخست‌وزیری دولت موقت؛ اصلاح با اعلان رسمی.",
  },
  {
    kind: "period",
    id: "ir-iri-pre-first-president",
    start_date: "1979-11-06",
    end_date: "1980-02-03",
    title_en: "Post-Bazargan: revolutionary bodies to first president",
    title_fa: "پس از بازرگان: نهادهای انقلابی تا نخستین رئیس‌جمهور",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 2,
    description_en:
      "Transitional period after the interim PM (Council of the Islamic Revolution and related bodies) until the first IRI president takes office (4 Feb 1980).",
    description_fa:
      "فاز انتقال پس از نخست‌وزیر موقت تا روی کار آمدن نخستین رئیس‌جمهور (۱۲/۱۳ بهمن ۱۳۵۸)؛ مبنا کلی.",
    tags: ["provisional", "council", "iran"],
    source_citation_en: "Placeholder band for display; use official IRI history for sub-period split.",
    source_citation_fa: "کلی؛ تقسیم دقیق با اعلان رسمی.",
  },
  {
    kind: "period",
    id: "ir-bani-sadr",
    start_date: "1980-02-04",
    end_date: "1981-06-22",
    title_en: "Abolhassan Banisadr (President, first IRI term)",
    title_fa: "ابوالحسن بنی‌صدر (رئیس‌جمهور، نخستین ریاست جمهوری)",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 3,
    description_en: "Elected 1980; term ends 22 June 1981 (removed, historical record); Islamic Republic of Iran presidency; dates per Britannica / IRI standard chronology.",
    description_fa: "نخستین رئیس‌جمهور پس از انقلاب؛ پایان ۲۲ ژوئن ۱۹۸۱ (طبق گاه‌شمار تاریخی)؛ بریتانیکا/تاریخ نهاد ریاست جمهوری.",
    tags: ["president", "iran"],
    source_citation_en: "IRI presidency, Britannica & standard IR chronology; verify against Majlis/official records.",
    source_citation_fa: "ریاست جمهوری؛ بریتانیکا و تداول نزد پژوهش‌های تاریخی—بررسی نهایی با اسناد رسمی.",
  },
  {
    kind: "period",
    id: "ir-mohammad-rajai",
    start_date: "1981-08-02",
    end_date: "1981-08-30",
    title_en: "Mohammad-Ali Rajai (President)",
    title_fa: "محمدعلی رجایی (رئیس‌جمهور)",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 3,
    description_en: "Assassination ends term August 1981; very short incumbency.",
    description_fa: "دوره کوتاه؛ پایان با ترور مرداد ۶۰.",
    tags: ["president", "iran"],
    source_citation_en: "Britannica / IRI public record for Rajai (Aug 1981).",
    source_citation_fa: "مرداد ۶۰ (بریتانیکا/رکورد متداول).",
  },
  {
    kind: "period",
    id: "ir-khamenei-pres",
    start_date: "1981-10-13",
    end_date: "1989-08-02",
    title_en: "Ali Khamenei (President, before becoming Supreme Leader)",
    title_fa: "سیدعلی خامنه‌ای (رئیس‌جمهور، پیش از رهبری)",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 3,
    description_en: "Two full terms as president, then accession to Supreme Leadership in 1989; split from leadership role in later era.",
    description_fa: "دو دوره رئیس‌جمهوری؛ سپس رهبری از ۱۳۶۸.",
    tags: ["president", "iran"],
    source_citation_en: "13 Oct 1981 – 2 Aug 1989; Britannica / IRI term listing.",
    source_citation_fa: "از ۲۱ مهر ۱۳۶۰ تا ۱۱ مرداد ۱۳۶۸.",
  },
  {
    kind: "period",
    id: "ir-rafsanjani",
    start_date: "1989-08-03",
    end_date: "1997-08-04",
    title_en: "Akbar Hashemi Rafsanjani (President)",
    title_fa: "اکبر هاشمی رفسنجانی (رئیس‌جمهور)",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 3,
    description_en: "Reconstruction term(s), post-war economy; per standard IRI presidencies.",
    description_fa: "دوره بازسازی پس‌ازجنگ.",
    tags: ["president", "iran"],
    source_citation_en: "Aug 1989 – Aug 1997 (IR presidency; Britannica).",
    source_citation_fa: "مرداد ۶۸ – مرداد ۷۶.",
  },
  {
    kind: "period",
    id: "ir-khatami",
    start_date: "1997-08-04",
    end_date: "2005-08-03",
    title_en: "Mohammad Khatami (President)",
    title_fa: "سیدمحمد خاتمی (رئیس‌جمهور)",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 3,
    description_en: "Two terms, reformist opening and civil society agenda.",
    description_fa: "دو دوره، چشم‌انداز اصلاحات و جامعه مدنی.",
    tags: ["president", "iran"],
    source_citation_en: "Aug 1997 – Aug 2005 (IR presidency, Britannica).",
    source_citation_fa: "مرداد ۷۶ – مرداد ۸۴.",
  },
  {
    kind: "period",
    id: "ir-ahmadinejad",
    start_date: "2005-08-03",
    end_date: "2013-08-03",
    title_en: "Mahmoud Ahmadinejad (President)",
    title_fa: "محمود احمدی‌نژاد (رئیس‌جمهور)",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 3,
    description_en: "Two terms, nuclear file and energy diplomacy; popular base and contested re-election 2009.",
    description_fa: "دو دوره، پرونده هسته‌ای و تداوم مطالبات اجتماعی.",
    tags: ["president", "iran"],
    source_citation_en: "Aug 2005 – Aug 2013 (IR presidency).",
    source_citation_fa: "مرداد ۸۴ – مرداد ۹۲.",
  },
  {
    kind: "period",
    id: "ir-rouhani",
    start_date: "2013-08-03",
    end_date: "2021-08-03",
    title_en: "Hassan Rouhani (President)",
    title_fa: "حسن روحانی (رئیس‌جمهور)",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 3,
    description_en: "Nuclear deal (JCPOA) and sanctions cycle; two terms per standard IRI incumbency.",
    description_fa: "دوره برجام و موج تحریم و دیپلماسی، دو دوره کامل.",
    tags: ["president", "iran"],
    source_citation_en: "Aug 2013 – Aug 2021.",
    source_citation_fa: "مرداد ۹۲ – مرداد ۰۰ (۱۴۰۰).",
  },
  {
    kind: "period",
    id: "ir-raisi",
    start_date: "2021-08-03",
    end_date: "2024-05-19",
    title_en: "Ebrahim Raisi (President)",
    title_fa: "ابراهیم رئیسی (رئیس‌جمهور)",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 3,
    description_en: "Term cut short 19 May 2024; dates per public record and international reporting.",
    description_fa: "پایان دوره ۳۰ اردیبهشت ۱۴۰۳ (۲۹/۳۰ اردیبهشت در گزارش‌ها)؛ اصلاح با منبع رسمی.",
    tags: ["president", "iran"],
    source_citation_en: "Aug 2021 – May 2024 (end by death; Britannica / newswire consensus).",
    source_citation_fa: "۱۴۰۰–۱۴۰۳ (پایان با فوت)؛ اصلاح با اعلام نهایی.",
  },
  {
    kind: "period",
    id: "ir-mokhber-acting",
    start_date: "2024-05-19",
    end_date: "2024-07-30",
    title_en: "Mohammad Mokhber (Acting President)",
    title_fa: "محمد مخبر (رئیس‌جمهور موقت)",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 3,
    description_en: "Interim presidency to inauguration of the next president; end aligned with new president taking office (Jul 30, 2024, standard reporting).",
    description_fa: "موقت تا برگزاری و تحلیف دولت جدید.",
    tags: ["president", "iran", "acting"],
    source_citation_en: "Acting period: verify exact handover date against IRI public schedule.",
    source_citation_fa: "تاریخ دقیق تحویل دولت را با اعلان رسمی تطبیق دهید.",
  },
  {
    kind: "period",
    id: "ir-pezeshkian",
    start_date: "2024-07-30",
    end_date: "2030-12-31",
    title_en: "Masoud Pezeshkian (President, incumbent)",
    title_fa: "مسعود پزشکیان (رئیس‌جمهور، دوره جاری)",
    lane: "iran_leadership",
    category: "iran_leadership",
    importance: 3,
    description_en: "Elected 2024; end date in seed is a display placeholder on the same pattern as other ongoing IRI/leadership bands; adjust when a fixed end is known.",
    description_fa: "انتخاب ۱۴۰۳؛ پایان نمایش فقط مکان‌نگهدار تا تعیین قطعی.",
    tags: ["president", "iran"],
    source_citation_en: "From inauguration ~30 July 2024; ongoing—confirm end when term completes.",
    source_citation_fa: "شروع ≈ ۹ مرداد ۱۴۰۳؛ در حال اجرا.",
  },
];

export const LEADERSHIP_BAND_ALL: readonly BandTimelinePeriodEvent[] = [
  ...LEADERSHIP_BAND_US,
  ...LEADERSHIP_BAND_IR,
];

export const IR_LEADERSHIP_COUNT = LEADERSHIP_BAND_IR.length;
export const US_LEADERSHIP_COUNT = LEADERSHIP_BAND_US.length;
