import type { BandTimelineEvent } from "./types";
import { LEADERSHIP_BAND_ALL } from "./leadership-seed";
import { SIGNALMAP_BALKAN_AND_WAR_BAND } from "../signalmap-war-canonical";
import { SIGNALMAP_OIL_BAND } from "../signalmap-oil-canonical";
import { MACRO_CRISIS_BAND_PERIODS } from "../signalmap-macro-crisis-periods";
import { ISRAEL_IRAN_US_BAND } from "../signalmap-israel-iran-us-conflict";
import { SIGNALMAP_FX_BAND } from "../signalmap-fx-band-canonical";

/**
 * Band swimlane seed. Ids are aligned with dot `SIGNALMAP_TIMELINE_SEED` and shared canons
 * (e.g. `SIGNALMAP_OIL_*`, `g-1973-embargo`); period-only rows use dedicated ids
 * (e.g. `ir-jcpoa-era` vs point `ir-jcpoa` on the dot chart).
 * Major **periods** use `kind: "period"` (horizontal bands); one-off episodes stay `point` when needed.
 */
export const BAND_TIMELINE_SEED: BandTimelineEvent[] = [
  {
    kind: "period",
    id: "b-ww1",
    start_date: "1914-07-28",
    end_date: "1918-11-11",
    title_en: "World War I",
    title_fa: "جنگ جهانی اول",
    lane: "global_wars",
    category: "global_wars",
    region: "global",
    importance: 3,
    description_en: "Allied and Central Powers conflict in Europe and beyond; ends with the Armistice of 11 November 1918.",
    description_fa: "جنگ اتحادها و قدرت‌های محور در اروپا و مناطق دیگر؛ پایان با آتش‌بس ۱۱ نوامبر ۱۹۱۸.",
  },
  {
    kind: "period",
    id: "b-ww2",
    start_date: "1939-09-01",
    end_date: "1945-09-02",
    title_en: "World War II",
    title_fa: "جنگ جهانی دوم",
    lane: "global_wars",
    category: "global_wars",
    region: "global",
    importance: 3,
    description_en: "Global war in Europe, Asia, and the Pacific; ends with the surrender of Japan in September 1945.",
    description_fa: "جنگ گسترده در اروپا، آسیا و اقیانوس آرام؛ پایان با تسلیم ژاپن در سپتامبر ۱۹۴۵.",
  },
  {
    kind: "period",
    id: "b-cold-war",
    start_date: "1947-03-12",
    end_date: "1991-12-26",
    title_en: "Cold War",
    title_fa: "جنگ سرد",
    lane: "global",
    category: "global",
    importance: 3,
    description_en: "Geopolitical and ideological standoff between US-led and Soviet-led blocs after WWII.",
    description_fa: "رقابت ژئوپلیتیک و ایدئولوژیک بلوک غرب و شوروی پس از جنگ جهانی دوم.",
  },
  ...SIGNALMAP_FX_BAND,
  ...MACRO_CRISIS_BAND_PERIODS,
  ...SIGNALMAP_OIL_BAND,
  {
    kind: "point",
    id: "ir-rev-79",
    date: "1979-02-11",
    title_en: "Iranian Revolution",
    title_fa: "انقلاب ایران",
    lane: "iran",
    category: "iran",
    importance: 3,
    description_en: "Fall of the Pahlavi monarchy and establishment of the Islamic Republic of Iran.",
    description_fa: "سقوط پادشاهی و استقرار جمهوری اسلامی.",
  },
  {
    kind: "period",
    id: "ir-iq-war",
    start_date: "1980-09-22",
    end_date: "1988-08-20",
    title_en: "Iran–Iraq War",
    title_fa: "جنگ ایران و عراق",
    lane: "middle_east_wars",
    category: "middle_east_wars",
    region: "middle_east",
    importance: 3,
    description_en: "Full-scale conventional war; heavy human and economic cost for both countries.",
    description_fa: "جنگ نسل‌کش؛ هزینه سنگین انسانی و اقتصادی برای طرفین.",
  },
  {
    kind: "period",
    id: "ir-jcpoa-era",
    start_date: "2015-07-14",
    end_date: "2018-05-08",
    title_en: "JCPOA / nuclear deal in force (US party)",
    title_fa: "برجام (آمریکا در برجام)",
    lane: "iran",
    category: "iran",
    importance: 3,
    description_en: "Joint action plan: nuclear limits for relief until US withdrawal (May 8, 2018). Dot timeline uses points `ir-jcpoa` and `ir-jcpoa-exit` for the two milestones.",
    description_fa: "نامه محدودسازی هسته‌ای و تخفیف تحریم‌ها تا خروج آمریکا؛ تایم‌لاین نقطه‌ای از `ir-jcpoa` و `ir-jcpoa-exit` استفاده می‌کند.",
  },
  {
    kind: "period",
    id: "ir-sanctions-max-pressure",
    start_date: "2018-05-08",
    end_date: "2021-01-20",
    title_en: "Maximum pressure sanctions",
    title_fa: "دور «حداکثر فشار» تحریمی",
    lane: "policy",
    category: "policy",
    importance: 3,
    description_en: "Expanded US oil and banking sanctions; severe trade and FX stress on the Iranian economy.",
    description_fa: "تشدید محدودیت نفتی و بانکی و فشار مضاعف بر اقتصاد و تجارت.",
  },
  {
    kind: "period",
    id: "g-ukraine-invasion-ongoing",
    start_date: "2022-02-24",
    end_date: "2026-12-31",
    title_en: "Russia’s invasion of Ukraine (ongoing)",
    title_fa: "جنگ روسیه و اوکراین",
    lane: "europe_wars",
    category: "europe_wars",
    region: "europe",
    importance: 3,
    description_en: "Full-scale war; dot chart also marks the invasion day as `g-ukraine-22`.",
    description_fa: "تأثیر بر انرژی و دیپلماسی و تحریم‌ها؛ تایم‌لاین نقطه‌ای از `g-ukraine-22` دارد.",
  },
  ...SIGNALMAP_BALKAN_AND_WAR_BAND,
  ...ISRAEL_IRAN_US_BAND,
  ...LEADERSHIP_BAND_ALL,
];
