import type { BandTimelineEvent } from "./types";

/**
 * Demo / dev seed: broad historical arcs and anchor points. Dates are calendar YYYY-MM-DD in UTC.
 */
export const BAND_TIMELINE_SEED: BandTimelineEvent[] = [
  {
    kind: "period",
    id: "b-cold-war",
    start_date: "1947-03-12",
    end_date: "1991-12-26",
    title_en: "Cold War",
    title_fa: "جنگ سرد",
    lane: "global",
    category: "global",
    importance: 3,
    description_en: "Geopolitical and ideological standoff between US-led and Soviet-led blocs after WWII.",
    description_fa: "رقابت ژئوپلیتیک و ایدئولوژیک بلوک غرب و شوروی پس از جنگ جهانی دوم.",
  },
  {
    kind: "period",
    id: "b-bretton-woods",
    start_date: "1944-07-22",
    end_date: "1971-08-15",
    title_en: "Bretton Woods era",
    title_fa: "نظم برتون‌وُدز",
    lane: "fx",
    category: "fx",
    importance: 3,
    description_en: "Dollar-gold par value system and fixed FX arrangements centered on the US dollar until Nixon shock.",
    description_fa: "سامانه تثبیت نرخ‌ها و پیوند دلار به طلا تا نقطه شکست نیكسون (۱۹۷۱).",
  },
  {
    kind: "point",
    id: "b-oil-shock-73",
    date: "1973-10-16",
    title_en: "1973 oil shock",
    title_fa: "شوک نفتی ۱۹۷۳",
    lane: "oil",
    category: "oil",
    importance: 3,
    description_en: "OPEC price decision and oil embargo, sharp rise in energy prices and macro volatility.",
    description_fa: "تصمیم قیمت اوپک و فشار بر بازار نفت و انرژی.",
  },
  {
    kind: "point",
    id: "b-ir-rev",
    date: "1979-02-11",
    title_en: "Iranian Revolution",
    title_fa: "انقلاب ایران",
    lane: "iran",
    category: "iran",
    importance: 3,
    description_en: "Fall of the Pahlavi monarchy and establishment of the Islamic Republic of Iran.",
    description_fa: "سقوط پادشاهی و استقرار جمهوری اسلامی.",
  },
  {
    kind: "period",
    id: "b-ir-iq",
    start_date: "1980-09-22",
    end_date: "1988-08-20",
    title_en: "Iran–Iraq War",
    title_fa: "جنگ ایران و عراق",
    lane: "war",
    category: "war",
    importance: 3,
    description_en: "Full-scale conventional war; heavy human and economic cost for both countries.",
    description_fa: "جنگ نسل‌کش؛ هزینه سنگین انسانی و اقتصادی برای طرفین.",
  },
  {
    kind: "period",
    id: "b-jcpoa",
    start_date: "2015-07-14",
    end_date: "2018-05-08",
    title_en: "JCPOA / nuclear deal in force (US in)",
    title_fa: "برجام (آمریکا در برجام)",
    lane: "iran",
    category: "iran",
    importance: 3,
    description_en: "Joint action plan: sanctions relief for nuclear limitations until US withdrawal (May 2018).",
    description_fa: "نامه محدودسازی هسته‌ای و رفع تحریم‌ها تا خروج آمریکا از برجام.",
  },
  {
    kind: "period",
    id: "b-max-pressure",
    start_date: "2018-05-08",
    end_date: "2021-01-20",
    title_en: "Maximum pressure sanctions",
    title_fa: "دور اِعمال «حداکثر فشار»",
    lane: "policy",
    category: "policy",
    importance: 2,
    description_en: "Expanded US oil and banking sanctions; severe trade and FX stress on the Iranian economy.",
    description_fa: "تشدید محدودیت نفتی و بانکی و فشار مضاعف بر اقتصاد و تجارت.",
  },
  {
    kind: "period",
    id: "b-covid",
    start_date: "2020-03-11",
    end_date: "2023-05-05",
    title_en: "COVID-19 pandemic (WHO PHEIC → end of global emergency)",
    title_fa: "همه‌گیری کرونا",
    lane: "global",
    category: "global",
    importance: 2,
    description_en: "Global public-health shock with deep economic and mobility impacts.",
    description_fa: "تأثیر گسترده سلامت و اقتصاد جهان.",
  },
  {
    kind: "period",
    id: "b-ukraine-war",
    start_date: "2022-02-24",
    end_date: "2026-12-31",
    title_en: "Russia’s invasion of Ukraine (ongoing)",
    title_fa: "جنگ روسیه و اوکراین",
    lane: "war",
    category: "war",
    importance: 3,
    description_en: "Full-scale war with global energy, security, and sanctions consequences.",
    description_fa: "تأثیر بر انرژی و دیپلماسی و تحریم‌های گسترده.",
  },
];
