import type { BandTimelineEvent } from "./types";

/**
 * Band swimlane seed. Ids are aligned with dot timeline `SIGNALMAP_TIMELINE_SEED` where the same
 * real-world episode appears (e.g. `g-1973-embargo`); period-only rows use dedicated ids
 * (e.g. `ir-jcpoa-era` vs point `ir-jcpoa` on the dot chart).
 */
export const BAND_TIMELINE_SEED: BandTimelineEvent[] = [
  {
    kind: "period",
    id: "b-cold-war",
    start_date: "1947-03-12",
    end_date: "1991-12-26",
    title_en: "Cold War",
    title_fa: "جنگ سرد",
    lane: "global",
    category: "global",
    importance: 3,
    description_en: "Geopolitical and ideological standoff between US-led and Soviet-led blocs after WWII.",
    description_fa: "رقابت ژئوپلیتیک و ایدئولوژیک بلوک غرب و شوروی پس از جنگ جهانی دوم.",
  },
  {
    kind: "period",
    id: "b-bretton-woods",
    start_date: "1944-07-22",
    end_date: "1971-08-15",
    title_en: "Bretton Woods era",
    title_fa: "نظم برتون‌وُدز",
    lane: "fx",
    category: "fx",
    importance: 3,
    description_en: "Dollar-gold par value system and fixed FX arrangements centered on the US dollar until Nixon shock.",
    description_fa: "سامانه تثبیت نرخ‌ها و پیوند دلار به طلا تا نقطه شکست نیكسون (۱۹۷۱).",
  },
  {
    kind: "point",
    id: "g-1973-embargo",
    date: "1973-10-16",
    title_en: "1973 oil shock",
    title_fa: "شوک نفتی ۱۹۷۳",
    lane: "oil",
    category: "oil",
    importance: 3,
    description_en: "OPEC price decision and oil embargo, sharp rise in energy prices and macro volatility.",
    description_fa: "تصمیم قیمت اوپک و فشار بر بازار نفت و انرژی.",
  },
  {
    kind: "point",
    id: "ir-rev-79",
    date: "1979-02-11",
    title_en: "Iranian Revolution",
    title_fa: "انقلاب ایران",
    lane: "iran",
    category: "iran",
    importance: 3,
    description_en: "Fall of the Pahlavi monarchy and establishment of the Islamic Republic of Iran.",
    description_fa: "سقوط پادشاهی و استقرار جمهوری اسلامی.",
  },
  {
    kind: "period",
    id: "ir-iq-war",
    start_date: "1980-09-22",
    end_date: "1988-08-20",
    title_en: "Iran–Iraq War",
    title_fa: "جنگ ایران و عراق",
    lane: "war",
    category: "war",
    importance: 3,
    description_en: "Full-scale conventional war; heavy human and economic cost for both countries.",
    description_fa: "جنگ نسل‌کش؛ هزینه سنگین انسانی و اقتصادی برای طرفین.",
  },
  {
    kind: "period",
    id: "ir-jcpoa-era",
    start_date: "2015-07-14",
    end_date: "2018-05-08",
    title_en: "JCPOA / nuclear deal in force (US party)",
    title_fa: "برجام (آمریکا در برجام)",
    lane: "iran",
    category: "iran",
    importance: 3,
    description_en: "Joint action plan: nuclear limits for relief until US withdrawal (May 8, 2018). Dot timeline uses points `ir-jcpoa` and `ir-jcpoa-exit` for the two milestones.",
    description_fa: "نامه محدودسازی هسته‌ای و تخفیف تحریم‌ها تا خروج آمریکا؛ تایم‌لاین نقطه‌ای از `ir-jcpoa` و `ir-jcpoa-exit` استفاده می‌کند.",
  },
  {
    kind: "period",
    id: "ir-sanctions-max-pressure",
    start_date: "2018-05-08",
    end_date: "2021-01-20",
    title_en: "Maximum pressure sanctions (phase)",
    title_fa: "دور اِعمال «حداکثر فشار»",
    lane: "policy",
    category: "policy",
    importance: 2,
    description_en: "Expanded US oil and banking sanctions; severe trade and FX stress on the Iranian economy.",
    description_fa: "تشدید محدودیت نفتی و بانکی و فشار مضاعف بر اقتصاد و تجارت.",
  },
  {
    kind: "period",
    id: "g-covid-pandemic-era",
    start_date: "2020-03-11",
    end_date: "2023-05-05",
    title_en: "COVID-19 pandemic (WHO emergency → end of global PHEIC)",
    title_fa: "همه‌گیری کرونا (چارچه WHO → پایان PHEIC جهانی)",
    lane: "global",
    category: "global",
    importance: 2,
    description_en: "Global public-health shock; dot chart marks WHO PHEIC (`g-covid-pheic`, Jan 30, 2020) as a point-in-time anchor.",
    description_fa: "تأثیر گسترده سلامت و اقتصاد؛ تایم‌لاین نقطه‌ای از `g-covid-pheic` دارد.",
  },
  {
    kind: "period",
    id: "g-ukraine-invasion-ongoing",
    start_date: "2022-02-24",
    end_date: "2026-12-31",
    title_en: "Russia’s invasion of Ukraine (ongoing)",
    title_fa: "جنگ روسیه و اوکراین",
    lane: "war",
    category: "war",
    importance: 3,
    description_en: "Full-scale war; dot chart also marks the invasion day as `g-ukraine-22`.",
    description_fa: "تأثیر بر انرژی و دیپلماسی و تحریم‌ها؛ تایم‌لاین نقطه‌ای از `g-ukraine-22` دارد.",
  },
];
