/** Country → region for aggregating minor nodes in All data network. */
export const COUNTRY_TO_REGION: Record<string, string> = {
  "United States": "North America",
  Canada: "North America",
  Mexico: "North America",
  Brazil: "South America",
  Venezuela: "South America",
  Argentina: "South America",
  Colombia: "South America",
  Ecuador: "South America",
  Chile: "South America",
  Peru: "South America",
  Germany: "Europe",
  Netherlands: "Europe",
  France: "Europe",
  Italy: "Europe",
  Spain: "Europe",
  Poland: "Europe",
  Belgium: "Europe",
  Greece: "Europe",
  "United Kingdom": "Europe",
  Norway: "Europe",
  EU: "Europe",
  Sweden: "Europe",
  Finland: "Europe",
  Portugal: "Europe",
  Romania: "Europe",
  Czechia: "Europe",
  Austria: "Europe",
  Switzerland: "Europe",
  Ireland: "Europe",
  Hungary: "Europe",
  Nigeria: "Africa",
  Angola: "Africa",
  Libya: "Africa",
  Algeria: "Africa",
  "South Africa": "Africa",
  Egypt: "Africa",
  Congo: "Africa",
  Gabon: "Africa",
  "Equatorial Guinea": "Africa",
  Ghana: "Africa",
  "Saudi Arabia": "Middle East",
  Iran: "Middle East",
  Iraq: "Middle East",
  UAE: "Middle East",
  Kuwait: "Middle East",
  Turkey: "Middle East",
  Qatar: "Middle East",
  Oman: "Middle East",
  Bahrain: "Middle East",
  Yemen: "Middle East",
  Jordan: "Middle East",
  Lebanon: "Middle East",
  Syria: "Middle East",
  Israel: "Middle East",
  Kazakhstan: "Central Asia",
  Azerbaijan: "Central Asia",
  Uzbekistan: "Central Asia",
  Turkmenistan: "Central Asia",
  China: "East Asia",
  Japan: "East Asia",
  "South Korea": "East Asia",
  Taiwan: "East Asia",
  "Hong Kong": "East Asia",
  Mongolia: "East Asia",
  India: "South Asia",
  Pakistan: "South Asia",
  Bangladesh: "South Asia",
  "Sri Lanka": "South Asia",
  Nepal: "South Asia",
  Indonesia: "Southeast Asia",
  Malaysia: "Southeast Asia",
  Singapore: "Southeast Asia",
  Thailand: "Southeast Asia",
  Vietnam: "Southeast Asia",
  Philippines: "Southeast Asia",
  Myanmar: "Southeast Asia",
  Cambodia: "Southeast Asia",
  "Brunei Darussalam": "Southeast Asia",
  Brunei: "Southeast Asia",
  Australia: "Oceania",
  "New Zealand": "Oceania",
  "Papua New Guinea": "Oceania",
};

export function getRegion(country: string): string {
  return COUNTRY_TO_REGION[country] ?? "Other";
}
