/**
 * Canonical oil/energy bands and point anchors for SignalMap. Single source: band and dot seeds
 * spread these exports (no copied rows). Importance: 3 = visible at widest zoom; 2 = with zoom
 * in or “Show more events” (`importanceDetail: "all"`).
 */
import type { BandTimelineEvent } from "./signalmap-band-timeline/types";
import type { SignalMapTimelineEvent } from "./signalmap-timeline/types";

const O = "oil" as const;

export const SIGNALMAP_OIL_BAND: BandTimelineEvent[] = [
  {
    kind: "period",
    id: "oil-1970s-crisis-era",
    start_date: "1973-01-01",
    end_date: "1980-12-31",
    title_en: "1970s oil crisis (shock era)",
    title_fa: "بحران نفتی دهه ۱۹۷۰ (دوره شوک)",
    lane: O,
    category: O,
    importance: 3,
    description_en: "OPEC assertiveness, embargoes, and stepwise real oil-price increases; stagflation and policy shifts in importers.",
    description_fa: "نقش پررنگ‌تر اوپک، تحریم و جهش تدریجی قیمت نفت حقیقی؛ تورم رکودی و اصلاح سیاست در واردکنندگان.",
  },
  {
    kind: "period",
    id: "oil-iran-rev-disruption-78-81",
    start_date: "1978-01-01",
    end_date: "1981-12-31",
    title_en: "Iran oil supply disruption (revolution and war onset)",
    title_fa: "اختلال عرضه نفت ایران (انقلاب و آغاز جنگ)",
    lane: O,
    category: O,
    importance: 3,
    description_en: "Falls in Iranian production and export uncertainty as the monarchy ends and the Iran–Iraq war nears; tight global market.",
    description_fa: "کاهش تولید/صادره و نوسان امنیتی از پایان سلطنت تا فاز آغاز جنگ فرسایشی و بازار جهانی تنگ‌تر.",
  },
  {
    kind: "period",
    id: "oil-2000s-commodity-boom",
    start_date: "2003-01-01",
    end_date: "2008-12-31",
    title_en: "2000s commodity boom (oil and materials)",
    title_fa: "رونق کالا/نفت دهه ۲۰۰۰",
    lane: O,
    category: O,
    importance: 3,
    description_en: "Rising China-led demand, tight supply cycles, and sharp price run-ups peaking in the 2007–2008 pre/GFC months.",
    description_fa: "رشد تقاضای تحت-رهبری چین و چرخه افت عرضه؛ جهش قیمت تا ماه‌های پیش/حین بحران ۲۰۰۸.",
  },
  {
    kind: "period",
    id: "oil-shale-expansion-era",
    start_date: "2010-01-01",
    end_date: "2019-12-31",
    title_en: "U.S. shale oil expansion era",
    title_fa: "دوره گسترش نفت شیل (آمریکا)",
    lane: O,
    category: O,
    importance: 3,
    description_en: "Rapid L48 supply growth, breakeven learning curves, and OPEC+ co-existence — transforms marginal pricing logic.",
    description_fa: "رشد سریع عرضه شیل ۴۸ ایالت؛ کاهش بریک‌اون/سیاست اوپک‌پلاس — منطق قیمت حاشیه‌ای عوض می‌شود.",
  },
  {
    kind: "period",
    id: "oil-covid-demand-shock-20-21",
    start_date: "2020-01-01",
    end_date: "2021-12-31",
    title_en: "COVID-19 oil demand shock",
    title_fa: "شوک تقاضای نفت (کووید ۲۰۲۰–۲۰۲۱)",
    lane: O,
    category: O,
    importance: 3,
    description_en: "Pandemic lockdowns and mobility collapse, storage stress, and partial rebound as economies reopen; extreme volatility in benchmarks.",
    description_fa: "تعطیلی-تردد؛ استرس سیلان ذخایر و ریکاوری فاصله‌دار اقتصادها؛ نوسان شدید نفت/گاز (شامل WTI) در اوج افت.",
  },
  {
    kind: "point",
    id: "g-1973-embargo",
    date: "1973-10-16",
    title_en: "1973 Arab oil embargo",
    title_fa: "تحریم نفتی اعراب ۱۹۷۳",
    lane: O,
    category: O,
    importance: 3,
    description_en: "OPEC+Arab producers’ export restrictions; sharp price and macro shock for major importers.",
    description_fa: "محدودیت صادرات (اوپک+عراب)؛ شوک مالی-کلان بزرگ برای واردکنندگان اصلی.",
  },
  {
    kind: "point",
    id: "g-1979-oil-shock",
    date: "1979-01-16",
    title_en: "1979 oil shock",
    title_fa: "شوک نفتی ۱۹۷۹",
    lane: O,
    category: O,
    importance: 3,
    description_en: "Iranian upheaval and follow-on OPEC realignments; second major real oil price spike of the decade.",
    description_fa: "ناآرامی ایران و بازتنظیم اوپک؛ دومین جهش بزرگ قیمت نفت حقیقی در همان دهه.",
  },
  {
    kind: "point",
    id: "g-1990-gulf-oil-shock",
    date: "1990-08-02",
    title_en: "1990 Gulf War oil shock",
    title_fa: "شوک نفتی جنگ خلیج ۱۹۹۰",
    lane: O,
    category: O,
    importance: 3,
    description_en: "Iraq’s invasion of Kuwait; acute supply and risk premium spike in world oil and products.",
    description_fa: "تصرف کویت و جهش بزرگ-کوتاه ریسک عرضه و پریمیوم در بازار جهانی نفت/فراورش.",
  },
  {
    kind: "point",
    id: "g-2008-oil-spike",
    date: "2008-07-11",
    title_en: "2008 oil price spike",
    title_fa: "اوج قیمت نفت ۲۰۰۸",
    lane: O,
    category: O,
    importance: 3,
    description_en: "Brent–WTI near pre-GFC records; food–fuel and macro-stress as crisis intensifies in H2 2008.",
    description_fa: "نزدیک رکورد سابق (پیش-GFC)؛ بحران غذا-انرژی و فشار اقتصاد اصلی و شتاب بحران مالی در نیمه دوم ۲۰۰۸.",
  },
  {
    kind: "point",
    id: "g-2014-oil-collapse",
    date: "2014-11-27",
    title_en: "2014 oil price collapse",
    title_fa: "سقوط قیمت نفت ۲۰۱۴",
    lane: O,
    category: O,
    importance: 3,
    description_en: "OPEC and market-driven turning point: sustained fall from mid-2014, shale–OPEC overhang and price war dynamics.",
    description_fa: "نقطه گردان از اواسط ۲۰۱۴: سقوط پایدار؛ اثر شیل و افت‌-قیمت و منطق عرضه مازاد/جنگ-قیمت‌گذاری.",
  },
  {
    kind: "point",
    id: "g-2020-oil-crash",
    date: "2020-03-09",
    title_en: "2020 oil price crash (demand and OPEC+ break)",
    title_fa: "سقوط نفت ۲۰۲۰ (تقاضا و اختلاف اوپک‌پلاس)",
    lane: O,
    category: O,
    importance: 3,
    description_en: "Largest one-day % moves in a generation: demand shock from pandemic plus OPEC+ disagreement and supply surge.",
    description_fa: "نوسان٪-روزانه ماندگار در نسل؛ شوک کرونا به اضافه اختلاف/موج عرضه اوپک و شرکا.",
  },
  {
    kind: "point",
    id: "g-2022-oil-swing",
    date: "2022-03-08",
    title_en: "2022 energy shock (Russia’s invasion of Ukraine)",
    title_fa: "شوک انرژی ۲۰۲۲ (جنگ روسیه و اوکراین)",
    lane: O,
    category: O,
    importance: 3,
    description_en: "Brent and gas benchmarks jump; import substitution, sanctions, and oil-market re-allocation; complements war timeline anchors.",
    description_fa: "جهش نفت/گاز و جایگزینی-تحریم در زنجیره انرژی (همراه با تایم‌لاینِ جنگ/تحریم).",
  },
];

/**
 * Point-only rows for the dot timeline (multi-year oil eras appear as bands, not as dot spans here).
 */
export const SIGNALMAP_OIL_TIMELINE: SignalMapTimelineEvent[] = [
  {
    id: "g-1973-embargo",
    date_start: "1973-10-16",
    title_en: "1973 Arab oil embargo",
    title_fa: "تحریم نفتی اعراب ۱۹۷۳",
    description_en: "OPEC+Arab producers’ export restrictions; sharp price and macro shock for major importers.",
    description_fa: "محدودیت صادرات (اوپک+عراب)؛ شوک مالی-کلان بزرگ برای واردکنندگان اصلی.",
    category: O,
    tags: ["opec", "yom-kippur", "embargo"],
    importance: 3,
  },
  {
    id: "g-1979-oil-shock",
    date_start: "1979-01-16",
    title_en: "1979 oil shock",
    title_fa: "شوک نفتی ۱۹۷۹",
    description_en: "Iranian upheaval and follow-on OPEC realignments; second major real oil price spike of the decade.",
    description_fa: "ناآرامی ایران و بازتنظیم اوپک؛ دومین جهش بزرگ قیمت نفت حقیقی در همان دهه.",
    category: O,
    tags: ["1979", "iran", "opec", "shock"],
    importance: 3,
  },
  {
    id: "g-1990-gulf-oil-shock",
    date_start: "1990-08-02",
    title_en: "1990 Gulf War oil shock",
    title_fa: "شوک نفتی جنگ خلیج ۱۹۹۰",
    description_en: "Iraq’s invasion of Kuwait; acute supply and risk premium spike in world oil and products (oil-market lens; war remains on war layer).",
    description_fa: "تصرف کویت و جهش ریسک/پریمیوم (زاویه بازار نفت — جنگ اصلی در لایه جنگ).",
    category: O,
    tags: ["gulf", "iraq", "kuwait", "oil"],
    importance: 3,
  },
  {
    id: "g-2008-oil-spike",
    date_start: "2008-07-11",
    title_en: "2008 oil price spike",
    title_fa: "اوج قیمت نفت ۲۰۰۸",
    description_en: "Brent–WTI near pre-GFC records; oil-specific stress in a broader macro crisis quarter.",
    description_fa: "نزدیک رکورد پیش-GFC و تنش انرژی داخل بحران ماکرو/مالی ۲۰۰۸.",
    category: O,
    tags: ["brent", "gfc-2008", "commodities"],
    importance: 3,
  },
  {
    id: "g-2014-oil-collapse",
    date_start: "2014-11-27",
    title_en: "2014 oil price collapse",
    title_fa: "سقوط قیمت نفت ۲۰۱۴",
    description_en: "Sustained post-mid-2014 fall: OPEC, shale, and re-pricing of long-cycle supply; durable shift in market governance.",
    description_fa: "سقوط پس از اواسط ۲۰۱۴: اوپک+شیل و اصلاح طولی قیمت/نظام بازار نفت.",
    category: O,
    tags: ["brent", "shale", "opec"],
    importance: 3,
  },
  {
    id: "g-2020-oil-crash",
    date_start: "2020-03-09",
    title_en: "2020 oil price crash (demand and OPEC+ break)",
    title_fa: "سقوط نفت ۲۰۲۰ (تقاضا و اختلاف اوپک‌پلاس)",
    description_en: "Pandemic demand shock plus a sharp OPEC+ rupture; extreme one-day % moves; distinct from the April 2020 WTI contract low.",
    description_fa: "تقاضای ساقط کرونا + اختلاف اوپک+؛ افت٪-روزانه افراطی (منفاوت کف قرارداد WTI در آوریل ۲۰۲۰).",
    category: O,
    tags: ["wti", "pandemic", "opec-plus", "2020"],
    importance: 3,
  },
  {
    id: "g-2022-oil-swing",
    date_start: "2022-03-08",
    title_en: "2022 energy shock (Russia’s invasion of Ukraine)",
    title_fa: "شوک انرژی ۲۰۲۲ (جنگ روسیه و اوکراین)",
    description_en: "Brent and gas benchmarks spike; policy responses in importers; volatile macro cross-currents (aligned with the invasion time anchor on the war layer).",
    description_fa: "جهش نفت/گاز؛ اقدام واردکنندگان (هم‌زمان با تایم‌لاین نقطه‌ای حمله به اوکراین).",
    category: O,
    tags: ["brent", "sanctions", "volatility", "russia", "2022"],
    importance: 3,
  },
];
