/**
 * Canonical FX / monetary regime events for the SignalMap band swimlane. Bretton–Nixon–Plaza–GFC
 * and Iran rial stress anchors. Importance: 3 = default wide zoom; 2 = with zoom in or “all”.
 */
import type { BandTimelineEvent } from "./signalmap-band-timeline/types";

const F = "fx" as const;

export const SIGNALMAP_FX_BAND: BandTimelineEvent[] = [
  {
    kind: "period",
    id: "b-bretton-woods",
    start_date: "1944-07-22",
    end_date: "1971-08-15",
    title_en: "Bretton Woods era",
    title_fa: "نظم برتون‌وُدز",
    lane: F,
    category: F,
    importance: 3,
    description_en: "Dollar-gold par value and fixed exchange arrangements; anchor currency until convertibility ends.",
    description_fa: "نرخ ثابت و پیوند دلار به طلا تا پایان تبدیل‌پذیری ۱۹۷۱.",
  },
  {
    kind: "point",
    id: "fx-nixon-gold",
    date: "1971-08-15",
    title_en: "Nixon shock: gold convertibility suspended",
    title_fa: "شوک نیکسون: تعطیلی تبدیل طلا",
    lane: F,
    category: F,
    importance: 3,
    description_en: "U.S. closes the gold window; end of the Bretton Woods par value system as designed.",
    description_fa: "تعطیلی پنجره طلای دلار؛ پایان نظم برتون‌وُدز به‌صورت طراحی‌شده.",
  },
  {
    kind: "point",
    id: "fx-plaza-accord",
    date: "1985-09-22",
    title_en: "Plaza Accord (G5, coordinated USD depreciation)",
    title_fa: "تفاهم پلازا (G5 کاهش هم‌آهنگ ارزش دلار)",
    lane: F,
    category: F,
    importance: 3,
    description_en: "Major economies agree to intervene to lower an overvalued U.S. dollar; landmark FX-diplomacy case.",
    description_fa: "تصمیم ۵ اقتصاد اصلی برای اصلاح افراط ارزش دلار؛ اقدام تطبیق‌شده، نمونه مهم دیپلماسی ارز.",
  },
  {
    kind: "point",
    id: "fx-asia-97",
    date: "1997-07-02",
    title_en: "Asian financial crisis (float / contagion start)",
    title_fa: "بحران مالی آسیا (رهاکردن بات/سرایت)",
    lane: F,
    category: F,
    importance: 2,
    description_en: "Thailand abandons baht peg; region-wide credit and FX stress; IMF programs and structural critique.",
    description_fa: "رها کردن بات و سرایت اعتباری-ارزی؛ برنامه صندوق و بحث اصلاحات ساختاری.",
  },
  {
    kind: "point",
    id: "fx-euro-launch",
    date: "1999-01-01",
    title_en: "Euro launch (EMU Phase 1–3, electronic)",
    title_fa: "راه‌اندازی یورو (یورو الکترونیک EMU، فاز آغازین)",
    lane: F,
    category: F,
    importance: 3,
    description_en: "Currency union goes live in electronic form; long-run trade and reserve implications.",
    description_fa: "شروع اتحاد پولی (الکترونیک)؛ اثر ماندگار بر ذخایر-تجارت اروپا/جهان.",
  },
  {
    kind: "period",
    id: "fx-lane-gfc-2007-2009",
    start_date: "2007-08-09",
    end_date: "2009-12-31",
    title_en: "Global Financial Crisis (FX, dollar, cross-border credit)",
    title_fa: "بحران مالی جهانی (نقدینگی و دلار/اعتبار)",
    lane: F,
    category: F,
    importance: 3,
    description_en: "Dollar-funding stress, G-SIB resolution, and massive central-bank and FX-swap backstops; complements global GFC period.",
    description_fa: "تنگی مالی-دلاری بانک‌های بزرگ و پشتیبانی اضطرار؛ مکمّل دوره GFC لایه جهانی.",
  },
  {
    kind: "period",
    id: "ir-fx-dual-market-era",
    start_date: "2010-10-20",
    end_date: "2018-04-20",
    title_en: "Iran: official / parallel & dual-rate period (illustrative)",
    title_fa: "دوره چند-نرخ/موازی/رسمی ۱۴۰–۹۷ (لنگر نمونه)",
    lane: F,
    category: F,
    importance: 2,
    description_en: "Illustrative window when official and unregulated/parallel rial/USD levels diverged sharply; exact regime dates vary by market.",
    description_fa: "نمونه اختلاف ماندگار نرخ رسمی و بازار آزاد/موازی؛ بیشینه روزانه را با میکرو-کالا تطبیق دهید.",
  },
  {
    kind: "period",
    id: "ir-fx-2018-devaluation-spike",
    start_date: "2018-04-20",
    end_date: "2018-12-31",
    title_en: "Iran 2018 rial/FX devaluation (sanctions, JCPOA exit context)",
    title_fa: "افت/تهدید ۹۷-۹۸: ریال و اثر برجام/فشار (زمینه اصلاح ۹۵)",
    lane: F,
    category: F,
    importance: 2,
    description_en: "Sharp rial stress after U.S. policy shift; unification debate and import inflation; use as a macro/FX chapter anchor.",
    description_fa: "تشدید افت/کشمکش ۹۸ بعد از اعلام/خروج کاخ سفید؛ اصلاح/یکسان‌سازی ۹۵ در روایت اقتصاد.",
  },
  {
    kind: "period",
    id: "ir-fx-open-2022-2025",
    start_date: "2022-01-01",
    end_date: "2025-12-31",
    title_en: "Iran open / parallel rial: sustained devaluation (2022–2025, illustrative end)",
    title_fa: "نرخ آزاد-موازی: فشار ۱۴۰۱–امروز (پایان نمونه ۱۴۰۵)",
    lane: F,
    category: F,
    importance: 2,
    description_en: "Multi-year rial/USD and inflation episode in reporting and data platforms; end date in seed is for display; refine from official/primary sources.",
    description_fa: "تداوم افت-شوک/تورم در بستر اعلان‌ها—پایان نمونه ۱۴۰۵؛ با منبع اصلح به‌روز شود.",
  },
];
