import type { BandTimelineEvent } from "./signalmap-band-timeline/types";
import type { SignalMapTimelineEvent } from "./signalmap-timeline/types";

const P = "political" as const;
const L = "middle_east_political" as const;

/**
 * Arab Spring: dot timeline (political) + band swimlane (ME political row, separate from ME wars).
 * Main phase = importance 3; country windows = 1 (visible when zoomed in or “show all” importance).
 */
export const ARAB_SPRING_TIMELINE_DOT: SignalMapTimelineEvent[] = [
  {
    id: "arab-spring",
    date_start: "2010-12-01",
    date_end: "2012-12-31",
    title_en: "Arab Spring",
    title_fa: "بهار عربی",
    description_en:
      "Umbrella label for the wave of protests, uprisings, and regime crises across the Arab world; dates are a display band (regional timing varies by country).",
    description_fa:
      "موج اعتراضات و بحران‌های سیاسی در بسیاری از کشورهای عرب؛ این بازه نمادین است و زمان دقیق هر سرزمین متفاوت است.",
    category: P,
    tags: ["arab-spring", "mideast", "protest"],
    importance: 3,
  },
  {
    id: "arab-spring-tunisia",
    date_start: "2010-12-17",
    date_end: "2011-01-14",
    title_en: "Tunisia: Sidi Bouzid to Ben Ali exit",
    title_fa: "تونس: از سیدی‌بوزید تا کناره‌گیری بن‌علی",
    description_en: "Protests from late 2010 culminate in the fall of the Ben Ali government (14 Jan 2011).",
    description_fa: "تظاهرات پایان ۲۰۱۰–اوایل ۲۰۱۱ و سقوط دولت بن‌علی (۲۴ دی ۱۳۸۹).",
    category: P,
    tags: ["arab-spring", "tunisia"],
    importance: 1,
  },
  {
    id: "arab-spring-egypt",
    date_start: "2011-01-25",
    date_end: "2011-02-11",
    title_en: "Egypt: 25 Jan uprising to Mubarak’s exit",
    title_fa: "مصر: قیام ۲۵ ژانویه تا کناره‌گیری مبارک",
    description_en: "Mass mobilisation in Cairo and elsewhere; Mubarak steps down 11 February 2011.",
    description_fa: "بسیج گسترده و پایان دوره مبارک (۲۲ بهمن ۱۳۸۹).",
    category: P,
    tags: ["arab-spring", "egypt"],
    importance: 1,
  },
  {
    id: "arab-spring-libya",
    date_start: "2011-02-15",
    date_end: "2011-10-20",
    title_en: "Libya: 2011 uprising and civil war (phase shown)",
    title_fa: "لیبی: شورش و جنگ داخلی ۲۰۱۱ (فاز نمایش‌داده‌شده)",
    description_en: "Uprising and internationalised conflict; this band ends with the display placeholder for the fall of the old regime in 2011.",
    description_fa: "تشدید و مداخله بین‌المللی؛ باند پایان مکان‌نمای ۲۰۱۱.",
    category: P,
    tags: ["arab-spring", "libya"],
    importance: 1,
  },
  {
    id: "arab-spring-yemen",
    date_start: "2011-01-27",
    date_end: "2012-02-25",
    title_en: "Yemen: 2011–2012 transition phase",
    title_fa: "یمن: فاز انتقال ۱۳۹۰–۱۳۹۰ (۲۰۱۱–۲۰۱۲)",
    description_en: "Major protest cycle and power-transfer negotiations in the 2011–2012 window (Yemen’s crisis deepens afterward).",
    description_fa: "موج اعتراض و مذاکره قدرت در این پنجره؛ بحران پس‌ازآن ادامه می‌یابد.",
    category: P,
    tags: ["arab-spring", "yemen"],
    importance: 1,
  },
  {
    id: "arab-spring-syria",
    date_start: "2011-03-15",
    date_end: "2026-12-31",
    title_en: "Syria: uprising and civil war (from March 2011)",
    title_fa: "سوریه: خیزش و جنگ داخلی (از مارس ۲۰۱۱)",
    description_en:
      "From the March 2011 protest phase into protracted war; end date is a display placeholder (separate from the 2010–2012 ‘Arab Spring’ band).",
    description_fa:
      "از تظاهرات ۲۰۱۱ به‌سوی درگیری طولانی؛ پایان مکان‌نما برای نمایش و از باند ۲۰۱۰–۲۰۱۲ جداست.",
    category: P,
    tags: ["arab-spring", "syria", "mideast"],
    importance: 1,
  },
];

export const ARAB_SPRING_BAND: BandTimelineEvent[] = [
  {
    kind: "period",
    id: "arab-spring",
    start_date: "2010-12-01",
    end_date: "2012-12-31",
    title_en: "Arab Spring",
    title_fa: "بهار عربی",
    lane: L,
    category: "political",
    importance: 3,
    description_en: ARAB_SPRING_TIMELINE_DOT[0]!.description_en,
    description_fa: ARAB_SPRING_TIMELINE_DOT[0]!.description_fa,
    tags: ["arab-spring", "mideast"],
  },
  {
    kind: "period",
    id: "arab-spring-tunisia",
    start_date: "2010-12-17",
    end_date: "2011-01-14",
    title_en: "Tunisia (Sidi Bouzid to Ben Ali exit)",
    title_fa: "تونس (سیدی‌بوزید تا بن‌علی)",
    lane: L,
    category: "political",
    importance: 1,
    description_en: ARAB_SPRING_TIMELINE_DOT[1]!.description_en,
    description_fa: ARAB_SPRING_TIMELINE_DOT[1]!.description_fa,
    tags: ["arab-spring", "tunisia"],
  },
  {
    kind: "period",
    id: "arab-spring-egypt",
    start_date: "2011-01-25",
    end_date: "2011-02-11",
    title_en: "Egypt (25 Jan to Mubarak exit)",
    title_fa: "مصر (۲۵ ژانویه تا مبارک)",
    lane: L,
    category: "political",
    importance: 1,
    description_en: ARAB_SPRING_TIMELINE_DOT[2]!.description_en,
    description_fa: ARAB_SPRING_TIMELINE_DOT[2]!.description_fa,
    tags: ["arab-spring", "egypt"],
  },
  {
    kind: "period",
    id: "arab-spring-libya",
    start_date: "2011-02-15",
    end_date: "2011-10-20",
    title_en: "Libya (2011 uprising / war phase)",
    title_fa: "لیبی (شورش/جنگ ۲۰۱۱)",
    lane: L,
    category: "political",
    importance: 1,
    description_en: ARAB_SPRING_TIMELINE_DOT[3]!.description_en,
    description_fa: ARAB_SPRING_TIMELINE_DOT[3]!.description_fa,
    tags: ["arab-spring", "libya"],
  },
  {
    kind: "period",
    id: "arab-spring-yemen",
    start_date: "2011-01-27",
    end_date: "2012-02-25",
    title_en: "Yemen (2011–2012 transition window)",
    title_fa: "یمن (پنجره انتقال ۲۰۱۱–۲۰۱۲)",
    lane: L,
    category: "political",
    importance: 1,
    description_en: ARAB_SPRING_TIMELINE_DOT[4]!.description_en,
    description_fa: ARAB_SPRING_TIMELINE_DOT[4]!.description_fa,
    tags: ["arab-spring", "yemen"],
  },
  {
    kind: "period",
    id: "arab-spring-syria",
    start_date: "2011-03-15",
    end_date: "2026-12-31",
    title_en: "Syria: from March 2011 (uprising / war)",
    title_fa: "سوریه: از مارس ۲۰۱۱ (خیزش/جنگ)",
    lane: L,
    category: "political",
    importance: 1,
    description_en: ARAB_SPRING_TIMELINE_DOT[5]!.description_en,
    description_fa: ARAB_SPRING_TIMELINE_DOT[5]!.description_fa,
    tags: ["arab-spring", "syria"],
  },
];
