/**
 * Canonical major-conflict spans for SignalMap dot/band timelines (shared ids / dates; no
 * per-study duplication). Chart overlays that load `world_1900` get parallel rows in
 * `apps/api/src/signalmap/data/event_layers.py`.
 */
import type { BandTimelineEvent } from "./signalmap-band-timeline/types";
import type { SignalMapTimelineEvent } from "./signalmap-timeline/types";

const W = "war" as const;

/**
 * User-specified Balkan suite + other audited major war ranges. Importance: 1 = only when
 * zoomed in and/or `importanceDetail: "all"`; 2 = normal detail tier; 3 = landmark.
 */
export const SIGNALMAP_BALKAN_AND_WAR_RANGES: SignalMapTimelineEvent[] = [
  {
    id: "bosnian-war",
    date_start: "1992-04-01",
    date_end: "1995-12-14",
    title_en: "Bosnian War",
    title_fa: "جنگ بوسنی",
    description_en: "Bosnian War (Bosnia and Herzegovina, 1992–1995), ending with a negotiated settlement framework; regional displacement and state breakup patterns.",
    description_fa: "جنگ بوسنی و هرزگوین (۱۹۹۲–۱۹۹۵)؛ جابه‌جایی مردم و اثرهای منطقه‌ای.",
    category: W,
    tags: ["balkans", "bosnia", "yugoslavia"],
    importance: 3,
  },
  {
    id: "siege-of-sarajevo",
    date_start: "1992-04-05",
    date_end: "1996-02-29",
    title_en: "Siege of Sarajevo",
    title_fa: "محاصره سارایوو",
    description_en: "Protracted encirclement of Sarajevo; humanitarian and media-symbolic focus within the wider Bosnian war.",
    description_fa: "در محاصره طولانی، چهره بشردوستانه-رسانه‌ای برجسته در بستر وسیع‌تر بوسنی.",
    category: W,
    tags: ["balkans", "sarajevo", "siege"],
    importance: 1,
  },
  {
    id: "srebrenica-genocide",
    date_start: "1995-07-11",
    title_en: "Srebrenica genocide",
    title_fa: "نسل‌کشی سربرنیتسا",
    description_en: "11 July 1995 anchor: crimes later adjudicated in international law as genocide; subset of the Bosnian war.",
    description_fa: "۱۱ ژوئیه ۱۹۹۵: نقطه اصلی اقدامات بعدها جنایت علیه بشریت/نسل‌کشیشناخته‌شده.",
    category: W,
    tags: ["balkans", "srebrenica", "bosnia"],
    importance: 1,
  },
  {
    id: "kosovo-war",
    date_start: "1998-10-01",
    date_end: "1999-06-20",
    title_en: "Kosovo War",
    title_fa: "جنگ کوزوو",
    description_en: "Escalation from 1998 insurgency to 1999 NATO air campaign; Kosovo and wider Balkan order consequences.",
    description_fa: "تصاعد ۱۹۹۸ تا ۱۹۹۹؛ اثر سیاسی-نظامی بر وضعیت کوزوو/بالکان.",
    category: W,
    tags: ["balkans", "kosovo", "nato"],
    importance: 2,
  },
  {
    id: "gulf-war-1990-1991",
    date_start: "1990-08-02",
    date_end: "1991-02-28",
    title_en: "Gulf War (1990–1991)",
    title_fa: "جنگ خلیج فارس (۱۹۹۰–۱۹۹۱)",
    description_en: "Iraq’s annexation of Kuwait, coalition expulsion, large oil market shock. Span complements the 2 Aug 1990 day anchor.",
    description_fa: "ماجرا از اشغال کویت تا بحران میدانی و شوک بزرگ بازار نفت (بند روز-اشغال، جداگانه).",
    category: W,
    tags: ["gulf", "iraq", "kuwait", "oil"],
    importance: 2,
  },
  {
    id: "iraq-war-2003-2011",
    date_start: "2003-03-20",
    date_end: "2011-12-15",
    title_en: "Iraq War (U.S.–led intervention phase)",
    title_fa: "جنگ عراق (فاز مداخله سرباز-متحد)",
    description_en: "From invasion through transition; protracted counterinsurgency, supply risks. Coexists with 20 Mar 2003 start anchor (detail).",
    description_fa: "بازه مداخله تا دولت-انتقال؛ امنیت-عرضه نفت منطقه/پناهجویی/ایدئولوژی.",
    category: W,
    tags: ["iraq", "us", "mideast"],
    importance: 2,
  },
  {
    id: "afghanistan-war-2001-2021",
    date_start: "2001-10-07",
    date_end: "2021-08-30",
    title_en: "U.S.–led war in Afghanistan",
    title_fa: "جنگ افغانستان (متحد-رهبری آمریکا)",
    description_en: "From Operation Enduring Freedom through coalition presence to U.S. exit; macro backdrop for MENA, defence spend, and refugees.",
    description_fa: "تداوم ۲۰۰۱–۲۰۲۱ و خروج؛ بک‌دراپ منطقه-ای-امنیتی.",
    category: W,
    tags: ["afghanistan", "nato", "us"],
    importance: 2,
  },
  {
    id: "syria-civil-war",
    date_start: "2011-03-15",
    date_end: "2026-12-31",
    title_en: "Syrian civil war (ongoing conflict phase)",
    title_fa: "جنگ داخلی سوریه (فاز جاری)",
    description_en: "Protracted civil war, proxy fighting, and regional spillovers. End date a display band for ongoing conflict (refresh periodically). The March 2011 start anchor is detail-tier.",
    description_fa: "نزاع طولانی و پراکسی-منطقه‌ای؛ پایان مکان‌نمای است.",
    category: W,
    tags: ["syria", "mideast", "refugees"],
    importance: 2,
  },
  {
    id: "yemen-civil-war",
    date_start: "2014-09-16",
    date_end: "2026-12-31",
    title_en: "Yemen civil war (major phase)",
    title_fa: "جنگ داخلی یمن (فاز اصلی)",
    description_en: "Major escalation and Saudi-led coalition context from mid-2010s; end date a display band (refresh for ceasefires/negotiations).",
    description_fa: "تصاعد ۲۰۱۴ به بعد؛ اثر میدان-نفت-مسیر-حمل؛ پایان نمادین.",
    category: W,
    tags: ["yemen", "mideast", "red-sea"],
    importance: 2,
  },
];

/**
 * War-lane period bands: aligned ids/dates to dot; Sarajevo/Srebrenica importance 1 for
 * `minImportance` / zoom. Labels remain gated by on-screen width (BAND_LABEL_MIN_PX).
 */
export const SIGNALMAP_BALKAN_AND_WAR_BAND: BandTimelineEvent[] = [
  {
    kind: "period",
    id: "bosnian-war",
    start_date: "1992-04-01",
    end_date: "1995-12-14",
    title_en: "Bosnian War",
    title_fa: "جنگ بوسنی",
    lane: "europe_wars",
    category: "europe_wars",
    region: "europe",
    importance: 3,
    description_en: "Bosnian War (Bosnia and Herzegovina, 1992–1995), ending with a negotiated settlement framework; regional displacement and state breakup patterns.",
    description_fa: "جنگ بوسنی و هرزگوین (۱۹۹۲–۱۹۹۵)؛ جابه‌جایی مردم و اثرهای منطقه‌ای.",
  },
  {
    kind: "period",
    id: "siege-of-sarajevo",
    start_date: "1992-04-05",
    end_date: "1996-02-29",
    title_en: "Siege of Sarajevo",
    title_fa: "محاصره سارایوو",
    lane: "europe_wars",
    category: "europe_wars",
    region: "europe",
    importance: 1,
    description_en: "Protracted encirclement of Sarajevo; show at stronger zoom or “all” importance. Humanitarian and media focus within the wider war.",
    description_fa: "پایهٔ محصور طولانی؛ سطح جزئی/زوم قوی. لایه امداد-نماد-رسانه‌ای داخل بستر وسیع‌تر.",
  },
  {
    kind: "point",
    id: "srebrenica-genocide",
    date: "1995-07-11",
    title_en: "Srebrenica genocide (11 July 1995)",
    title_fa: "نسل‌کشی سربرنیتسا (۱۱ ژوئیه ۱۹۹۵)",
    lane: "europe_wars",
    category: "europe_wars",
    region: "europe",
    importance: 1,
    description_en: "Single-day anchor; importance 1 so it is subordinate to the Bosnian war band at default zoom. Legal qualification as genocide in international case law context.",
    description_fa: "لنگر یک‌روزه، اهمیت ۱ زیرا در زوم کلی باند اصلی است؛ اهمیت حقوقی-بین‌الملل.",
  },
  {
    kind: "period",
    id: "kosovo-war",
    start_date: "1998-10-01",
    end_date: "1999-06-20",
    title_en: "Kosovo War",
    title_fa: "جنگ کوزوو",
    lane: "europe_wars",
    category: "europe_wars",
    region: "europe",
    importance: 2,
    description_en: "Kosovo conflict, NATO 1999 air operation; mass displacement.",
    description_fa: "درگیری کوزوو و عملیات ۱۹۹۹ و آوارگی.",
  },
  {
    kind: "period",
    id: "gulf-war-1990-1991",
    start_date: "1990-08-02",
    end_date: "1991-02-28",
    title_en: "Gulf War (1990–1991)",
    title_fa: "جنگ خلیج فارس (۱۹۹۰–۱۹۹۱)",
    lane: "middle_east_wars",
    category: "middle_east_wars",
    region: "middle_east",
    importance: 2,
    description_en: "Iraq–Kuwait; coalition; oil shock window.",
    description_fa: "کویت-عراق؛ ئتلاف؛ شوک نفتی جدی.",
  },
  {
    kind: "period",
    id: "iraq-war-2003-2011",
    start_date: "2003-03-20",
    end_date: "2011-12-15",
    title_en: "Iraq War (U.S.–led phase)",
    title_fa: "جنگ عراق (فاز مورد)",
    lane: "middle_east_wars",
    category: "middle_east_wars",
    region: "middle_east",
    importance: 2,
    description_en: "U.S.–led intervention through transition; long insurgency phase; supply/price risk in global oil market.",
    description_fa: "مداخله-انتقال؛ امنیت-عرضه-نفت.",
  },
  {
    kind: "period",
    id: "afghanistan-war-2001-2021",
    start_date: "2001-10-07",
    end_date: "2021-08-30",
    title_en: "U.S.–led war in Afghanistan",
    title_fa: "جنگ افغانستان (رهبری آمریکا)",
    lane: "global_wars",
    category: "global_wars",
    region: "global",
    importance: 2,
    description_en: "2001–2021; exit policy anchor separate on dot.",
    description_fa: "۲۰۰۱–۲۰۲۱، خروج (نقطه نقطه‌ای جدا).",
  },
  {
    kind: "period",
    id: "syria-civil-war",
    start_date: "2011-03-15",
    end_date: "2026-12-31",
    title_en: "Syrian civil war (ongoing)",
    title_fa: "جنگ داخلی سوریه (جریان)",
    lane: "middle_east_wars",
    category: "middle_east_wars",
    region: "middle_east",
    importance: 2,
    description_en: "Protracted; band end placeholder for “ongoing”. The March 2011 point remains a start anchor in dot.",
    description_fa: "پایان مکان‌نمای ادامه؛ باند در زمان به‌روزشود.",
  },
  {
    kind: "period",
    id: "yemen-civil-war",
    start_date: "2014-09-16",
    end_date: "2026-12-31",
    title_en: "Yemen civil war (major phase)",
    title_fa: "جنگ داخلی یمن (فاز اصلی)",
    lane: "middle_east_wars",
    category: "middle_east_wars",
    region: "middle_east",
    importance: 2,
    description_en: "Houthi context and regional coalition; Bab el-Mandeb/Red sea risk; band end a placeholder (refresh for ceasefires).",
    description_fa: "میدان-خلیج-عدن؛ اثر مسیری-دریای سرخ؛ بروزرسانی.",
  },
];
